/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    FraudDeclineEmailRequest,
    FraudDeclineEmailRequestFromJSON,
    FraudDeclineEmailRequestToJSON,
    FraudLookupValuesResponse,
    FraudLookupValuesResponseFromJSON,
    FraudLookupValuesResponseToJSON,
    FraudRuleInsertRequest,
    FraudRuleInsertRequestFromJSON,
    FraudRuleInsertRequestToJSON,
    FraudRuleResponse,
    FraudRuleResponseFromJSON,
    FraudRuleResponseToJSON,
    FraudRuleSearchRequest,
    FraudRuleSearchRequestFromJSON,
    FraudRuleSearchRequestToJSON,
    FraudRulesResponse,
    FraudRulesResponseFromJSON,
    FraudRulesResponseToJSON,
} from '../models';

export interface DeclineEmailRequest {
    fraudDeclineEmailsRequest: FraudDeclineEmailRequest;
}

export interface DeleteFraudRuleRequest {
    fraudRuleOid: number;
}

export interface InsertFraudRuleRequest {
    fraudRuleInsertRequest: FraudRuleInsertRequest;
}

export interface SearchFraudRulesRequest {
    fraudRuleSearchRequest: FraudRuleSearchRequest;
    limit?: number;
    offset?: number;
    sort?: string;
}

/**
 * FraudApi - interface
 * 
 * @export
 * @interface FraudApiInterface
 */
export interface FraudApiInterface {
    /**
     * Adds one or more email addresses to the fraud decline list for this merchant account. 
     * @summary Decline emails during checkout fraud review
     * @param {FraudDeclineEmailRequest} fraudDeclineEmailsRequest Fraud decline emails request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FraudApiInterface
     */
    declineEmailRaw(requestParameters: DeclineEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Adds one or more email addresses to the fraud decline list for this merchant account. 
     * Decline emails during checkout fraud review
     */
    declineEmail(requestParameters: DeclineEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Deletes a fraud rule for this merchant account. 
     * @summary Delete a fraud rule
     * @param {number} fraudRuleOid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FraudApiInterface
     */
    deleteFraudRuleRaw(requestParameters: DeleteFraudRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a fraud rule for this merchant account. 
     * Delete a fraud rule
     */
    deleteFraudRule(requestParameters: DeleteFraudRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Returns the dropdown values required to build valid fraud rule insert and search requests. Includes rule types, failure actions, user actions, IP range types, AVS match types, the merchant\'s rotating transaction gateways, screen branding themes, countries, and affiliates. 
     * @summary Retrieve fraud rule lookup values
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FraudApiInterface
     */
    getFraudLookupValuesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FraudLookupValuesResponse>>;

    /**
     * Returns the dropdown values required to build valid fraud rule insert and search requests. Includes rule types, failure actions, user actions, IP range types, AVS match types, the merchant\'s rotating transaction gateways, screen branding themes, countries, and affiliates. 
     * Retrieve fraud rule lookup values
     */
    getFraudLookupValues(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FraudLookupValuesResponse>;

    /**
     * Creates a fraud rule for this merchant account. Field names in the request body are semantic (eg amount_threshold, email, ip_address). Call GET /v2/fraud/lookup_values for the list of valid rule_type, failure_action, and related dropdown values. The \'credit card matches\' rule type is not supported via REST. 
     * @summary Insert a fraud rule
     * @param {FraudRuleInsertRequest} fraudRuleInsertRequest Fraud rule insert request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FraudApiInterface
     */
    insertFraudRuleRaw(requestParameters: InsertFraudRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FraudRuleResponse>>;

    /**
     * Creates a fraud rule for this merchant account. Field names in the request body are semantic (eg amount_threshold, email, ip_address). Call GET /v2/fraud/lookup_values for the list of valid rule_type, failure_action, and related dropdown values. The \'credit card matches\' rule type is not supported via REST. 
     * Insert a fraud rule
     */
    insertFraudRule(requestParameters: InsertFraudRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FraudRuleResponse>;

    /**
     * Searches fraud rules for this merchant account using semantic filter fields. Pagination and sort are passed as query parameters (_limit, _offset, _sort). You will need to make multiple API calls in order to retrieve the entire result set since this API performs result set pagination. Results are capped at 10,000 records by ElasticSearch and the warning slot indicates when that cap was hit. Use more selective filters in that case. 
     * @summary Search fraud rules
     * @param {FraudRuleSearchRequest} fraudRuleSearchRequest Fraud rule search request
     * @param {number} [limit] The maximum number of records to return on this one API call. (Maximum 200)
     * @param {number} [offset] Pagination of the record set.  Offset is a zero based index.
     * @param {string} [sort] The sort order of the fraud rules.  See Sorting documentation for examples of using multiple values and sorting by ascending and descending.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FraudApiInterface
     */
    searchFraudRulesRaw(requestParameters: SearchFraudRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FraudRulesResponse>>;

    /**
     * Searches fraud rules for this merchant account using semantic filter fields. Pagination and sort are passed as query parameters (_limit, _offset, _sort). You will need to make multiple API calls in order to retrieve the entire result set since this API performs result set pagination. Results are capped at 10,000 records by ElasticSearch and the warning slot indicates when that cap was hit. Use more selective filters in that case. 
     * Search fraud rules
     */
    searchFraudRules(requestParameters: SearchFraudRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FraudRulesResponse>;

}

/**
 * 
 */
export class FraudApi extends runtime.BaseAPI implements FraudApiInterface {

    /**
     * Adds one or more email addresses to the fraud decline list for this merchant account. 
     * Decline emails during checkout fraud review
     */
    async declineEmailRaw(requestParameters: DeclineEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.fraudDeclineEmailsRequest === null || requestParameters.fraudDeclineEmailsRequest === undefined) {
            throw new runtime.RequiredError('fraudDeclineEmailsRequest','Required parameter requestParameters.fraudDeclineEmailsRequest was null or undefined when calling declineEmail.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("ultraCartOauth", ["fraud_write"]);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-ultracart-simple-key"] = this.configuration.apiKey("x-ultracart-simple-key"); // ultraCartSimpleApiKey authentication
        }

        const response = await this.request({
            path: `/fraud/decline_email`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FraudDeclineEmailRequestToJSON(requestParameters.fraudDeclineEmailsRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Adds one or more email addresses to the fraud decline list for this merchant account. 
     * Decline emails during checkout fraud review
     */
    async declineEmail(requestParameters: DeclineEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.declineEmailRaw(requestParameters, initOverrides);
    }

    /**
     * Deletes a fraud rule for this merchant account. 
     * Delete a fraud rule
     */
    async deleteFraudRuleRaw(requestParameters: DeleteFraudRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.fraudRuleOid === null || requestParameters.fraudRuleOid === undefined) {
            throw new runtime.RequiredError('fraudRuleOid','Required parameter requestParameters.fraudRuleOid was null or undefined when calling deleteFraudRule.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("ultraCartOauth", ["fraud_write"]);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-ultracart-simple-key"] = this.configuration.apiKey("x-ultracart-simple-key"); // ultraCartSimpleApiKey authentication
        }

        const response = await this.request({
            path: `/fraud/rules/{fraud_rule_oid}`.replace(`{${"fraud_rule_oid"}}`, encodeURIComponent(String(requestParameters.fraudRuleOid))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a fraud rule for this merchant account. 
     * Delete a fraud rule
     */
    async deleteFraudRule(requestParameters: DeleteFraudRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFraudRuleRaw(requestParameters, initOverrides);
    }

    /**
     * Returns the dropdown values required to build valid fraud rule insert and search requests. Includes rule types, failure actions, user actions, IP range types, AVS match types, the merchant\'s rotating transaction gateways, screen branding themes, countries, and affiliates. 
     * Retrieve fraud rule lookup values
     */
    async getFraudLookupValuesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FraudLookupValuesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("ultraCartOauth", ["fraud_read"]);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-ultracart-simple-key"] = this.configuration.apiKey("x-ultracart-simple-key"); // ultraCartSimpleApiKey authentication
        }

        const response = await this.request({
            path: `/fraud/lookup_values`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FraudLookupValuesResponseFromJSON(jsonValue));
    }

    /**
     * Returns the dropdown values required to build valid fraud rule insert and search requests. Includes rule types, failure actions, user actions, IP range types, AVS match types, the merchant\'s rotating transaction gateways, screen branding themes, countries, and affiliates. 
     * Retrieve fraud rule lookup values
     */
    async getFraudLookupValues(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FraudLookupValuesResponse> {
        const response = await this.getFraudLookupValuesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates a fraud rule for this merchant account. Field names in the request body are semantic (eg amount_threshold, email, ip_address). Call GET /v2/fraud/lookup_values for the list of valid rule_type, failure_action, and related dropdown values. The \'credit card matches\' rule type is not supported via REST. 
     * Insert a fraud rule
     */
    async insertFraudRuleRaw(requestParameters: InsertFraudRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FraudRuleResponse>> {
        if (requestParameters.fraudRuleInsertRequest === null || requestParameters.fraudRuleInsertRequest === undefined) {
            throw new runtime.RequiredError('fraudRuleInsertRequest','Required parameter requestParameters.fraudRuleInsertRequest was null or undefined when calling insertFraudRule.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("ultraCartOauth", ["fraud_write"]);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-ultracart-simple-key"] = this.configuration.apiKey("x-ultracart-simple-key"); // ultraCartSimpleApiKey authentication
        }

        const response = await this.request({
            path: `/fraud/rules`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FraudRuleInsertRequestToJSON(requestParameters.fraudRuleInsertRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FraudRuleResponseFromJSON(jsonValue));
    }

    /**
     * Creates a fraud rule for this merchant account. Field names in the request body are semantic (eg amount_threshold, email, ip_address). Call GET /v2/fraud/lookup_values for the list of valid rule_type, failure_action, and related dropdown values. The \'credit card matches\' rule type is not supported via REST. 
     * Insert a fraud rule
     */
    async insertFraudRule(requestParameters: InsertFraudRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FraudRuleResponse> {
        const response = await this.insertFraudRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Searches fraud rules for this merchant account using semantic filter fields. Pagination and sort are passed as query parameters (_limit, _offset, _sort). You will need to make multiple API calls in order to retrieve the entire result set since this API performs result set pagination. Results are capped at 10,000 records by ElasticSearch and the warning slot indicates when that cap was hit. Use more selective filters in that case. 
     * Search fraud rules
     */
    async searchFraudRulesRaw(requestParameters: SearchFraudRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FraudRulesResponse>> {
        if (requestParameters.fraudRuleSearchRequest === null || requestParameters.fraudRuleSearchRequest === undefined) {
            throw new runtime.RequiredError('fraudRuleSearchRequest','Required parameter requestParameters.fraudRuleSearchRequest was null or undefined when calling searchFraudRules.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['_limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['_offset'] = requestParameters.offset;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['_sort'] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("ultraCartOauth", ["fraud_read"]);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-ultracart-simple-key"] = this.configuration.apiKey("x-ultracart-simple-key"); // ultraCartSimpleApiKey authentication
        }

        const response = await this.request({
            path: `/fraud/rules/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FraudRuleSearchRequestToJSON(requestParameters.fraudRuleSearchRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FraudRulesResponseFromJSON(jsonValue));
    }

    /**
     * Searches fraud rules for this merchant account using semantic filter fields. Pagination and sort are passed as query parameters (_limit, _offset, _sort). You will need to make multiple API calls in order to retrieve the entire result set since this API performs result set pagination. Results are capped at 10,000 records by ElasticSearch and the warning slot indicates when that cap was hit. Use more selective filters in that case. 
     * Search fraud rules
     */
    async searchFraudRules(requestParameters: SearchFraudRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FraudRulesResponse> {
        const response = await this.searchFraudRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
