/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdjustLoyaltyPointsRequest
 */
export interface AdjustLoyaltyPointsRequest {
    /**
     * Description of this adjustment, 200 characters max
     * @type {string}
     * @memberof AdjustLoyaltyPointsRequest
     */
    description?: string;
    /**
     * The number of loyalty points to add to the ledger.  Use a negative number to debit points.  Required and may not be zero.
     * @type {number}
     * @memberof AdjustLoyaltyPointsRequest
     */
    loyalty_points?: number;
    /**
     * Optional order id if this adjustment is related to a particular order
     * @type {string}
     * @memberof AdjustLoyaltyPointsRequest
     */
    order_id?: string;
    /**
     * Optional days required for this adjustment to vest.  Leave null to use the merchant configured default.  Use zero for immediate vesting.
     * @type {number}
     * @memberof AdjustLoyaltyPointsRequest
     */
    vesting_days?: number;
}



/**
 * Check if a given object implements the AdjustLoyaltyPointsRequest interface.
 */
export function instanceOfAdjustLoyaltyPointsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AdjustLoyaltyPointsRequestFromJSON(json: any): AdjustLoyaltyPointsRequest {
    return AdjustLoyaltyPointsRequestFromJSONTyped(json, false);
}

export function AdjustLoyaltyPointsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdjustLoyaltyPointsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'loyalty_points': !exists(json, 'loyalty_points') ? undefined : json['loyalty_points'],
        'order_id': !exists(json, 'order_id') ? undefined : json['order_id'],
        'vesting_days': !exists(json, 'vesting_days') ? undefined : json['vesting_days'],
    };
}

export function AdjustLoyaltyPointsRequestToJSON(value?: AdjustLoyaltyPointsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'loyalty_points': value.loyalty_points,
        'order_id': value.order_id,
        'vesting_days': value.vesting_days,
    };
}

