/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutoOrderEmail
 */
export interface AutoOrderEmail {
    /**
     * 
     * @type {string}
     * @memberof AutoOrderEmail
     */
    bounce_diagnostic_code?: string;
    /**
     * Date/time that the email was bounced
     * @type {string}
     * @memberof AutoOrderEmail
     */
    bounce_dts?: string;
    /**
     * 
     * @type {string}
     * @memberof AutoOrderEmail
     */
    bounce_sub_type?: string;
    /**
     * 
     * @type {string}
     * @memberof AutoOrderEmail
     */
    bounce_type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AutoOrderEmail
     */
    clicked?: boolean;
    /**
     * Date/time that the email was clicked
     * @type {string}
     * @memberof AutoOrderEmail
     */
    clicked_dts?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AutoOrderEmail
     */
    delivered?: boolean;
    /**
     * Date/time that the email was delivered
     * @type {string}
     * @memberof AutoOrderEmail
     */
    delivery_dts?: string;
    /**
     * Email
     * @type {string}
     * @memberof AutoOrderEmail
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AutoOrderEmail
     */
    internal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AutoOrderEmail
     */
    message_id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AutoOrderEmail
     */
    opened?: boolean;
    /**
     * Date/time that the email was opened
     * @type {string}
     * @memberof AutoOrderEmail
     */
    opened_dts?: string;
    /**
     * 
     * @type {string}
     * @memberof AutoOrderEmail
     */
    reporting_mta?: string;
    /**
     * Date/time that the email was sent
     * @type {string}
     * @memberof AutoOrderEmail
     */
    send_dts?: string;
    /**
     * 
     * @type {string}
     * @memberof AutoOrderEmail
     */
    skip_reason?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AutoOrderEmail
     */
    skipped?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AutoOrderEmail
     */
    smtp_response?: string;
    /**
     * 
     * @type {string}
     * @memberof AutoOrderEmail
     */
    subject?: string;
}



/**
 * Check if a given object implements the AutoOrderEmail interface.
 */
export function instanceOfAutoOrderEmail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AutoOrderEmailFromJSON(json: any): AutoOrderEmail {
    return AutoOrderEmailFromJSONTyped(json, false);
}

export function AutoOrderEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoOrderEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bounce_diagnostic_code': !exists(json, 'bounce_diagnostic_code') ? undefined : json['bounce_diagnostic_code'],
        'bounce_dts': !exists(json, 'bounce_dts') ? undefined : json['bounce_dts'],
        'bounce_sub_type': !exists(json, 'bounce_sub_type') ? undefined : json['bounce_sub_type'],
        'bounce_type': !exists(json, 'bounce_type') ? undefined : json['bounce_type'],
        'clicked': !exists(json, 'clicked') ? undefined : json['clicked'],
        'clicked_dts': !exists(json, 'clicked_dts') ? undefined : json['clicked_dts'],
        'delivered': !exists(json, 'delivered') ? undefined : json['delivered'],
        'delivery_dts': !exists(json, 'delivery_dts') ? undefined : json['delivery_dts'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'internal': !exists(json, 'internal') ? undefined : json['internal'],
        'message_id': !exists(json, 'message_id') ? undefined : json['message_id'],
        'opened': !exists(json, 'opened') ? undefined : json['opened'],
        'opened_dts': !exists(json, 'opened_dts') ? undefined : json['opened_dts'],
        'reporting_mta': !exists(json, 'reporting_mta') ? undefined : json['reporting_mta'],
        'send_dts': !exists(json, 'send_dts') ? undefined : json['send_dts'],
        'skip_reason': !exists(json, 'skip_reason') ? undefined : json['skip_reason'],
        'skipped': !exists(json, 'skipped') ? undefined : json['skipped'],
        'smtp_response': !exists(json, 'smtp_response') ? undefined : json['smtp_response'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
    };
}

export function AutoOrderEmailToJSON(value?: AutoOrderEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bounce_diagnostic_code': value.bounce_diagnostic_code,
        'bounce_dts': value.bounce_dts,
        'bounce_sub_type': value.bounce_sub_type,
        'bounce_type': value.bounce_type,
        'clicked': value.clicked,
        'clicked_dts': value.clicked_dts,
        'delivered': value.delivered,
        'delivery_dts': value.delivery_dts,
        'email': value.email,
        'internal': value.internal,
        'message_id': value.message_id,
        'opened': value.opened,
        'opened_dts': value.opened_dts,
        'reporting_mta': value.reporting_mta,
        'send_dts': value.send_dts,
        'skip_reason': value.skip_reason,
        'skipped': value.skipped,
        'smtp_response': value.smtp_response,
        'subject': value.subject,
    };
}

