/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AutoOrder,
    AutoOrderFromJSON,
    AutoOrderFromJSONTyped,
    AutoOrderToJSON,
} from './AutoOrder';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface AutoOrderRebillResponse
 */
export interface AutoOrderRebillResponse {
    /**
     * 
     * @type {AutoOrder}
     * @memberof AutoOrderRebillResponse
     */
    auto_order?: AutoOrder;
    /**
     * 
     * @type {ModelError}
     * @memberof AutoOrderRebillResponse
     */
    error?: ModelError;
    /**
     * Why the rebill attempt did not succeed
     * @type {string}
     * @memberof AutoOrderRebillResponse
     */
    failure_reason?: string;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof AutoOrderRebillResponse
     */
    metadata?: ResponseMetadata;
    /**
     * True if a rebill was attempted during this call
     * @type {boolean}
     * @memberof AutoOrderRebillResponse
     */
    rebill_attempted?: boolean;
    /**
     * The order id created by a successful rebill
     * @type {string}
     * @memberof AutoOrderRebillResponse
     */
    rebill_order_id?: string;
    /**
     * True if the rebill attempt produced an order
     * @type {boolean}
     * @memberof AutoOrderRebillResponse
     */
    rebill_success?: boolean;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof AutoOrderRebillResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Warning}
     * @memberof AutoOrderRebillResponse
     */
    warning?: Warning;
}



/**
 * Check if a given object implements the AutoOrderRebillResponse interface.
 */
export function instanceOfAutoOrderRebillResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AutoOrderRebillResponseFromJSON(json: any): AutoOrderRebillResponse {
    return AutoOrderRebillResponseFromJSONTyped(json, false);
}

export function AutoOrderRebillResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoOrderRebillResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auto_order': !exists(json, 'auto_order') ? undefined : AutoOrderFromJSON(json['auto_order']),
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'failure_reason': !exists(json, 'failure_reason') ? undefined : json['failure_reason'],
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'rebill_attempted': !exists(json, 'rebill_attempted') ? undefined : json['rebill_attempted'],
        'rebill_order_id': !exists(json, 'rebill_order_id') ? undefined : json['rebill_order_id'],
        'rebill_success': !exists(json, 'rebill_success') ? undefined : json['rebill_success'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function AutoOrderRebillResponseToJSON(value?: AutoOrderRebillResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auto_order': AutoOrderToJSON(value.auto_order),
        'error': ModelErrorToJSON(value.error),
        'failure_reason': value.failure_reason,
        'metadata': ResponseMetadataToJSON(value.metadata),
        'rebill_attempted': value.rebill_attempted,
        'rebill_order_id': value.rebill_order_id,
        'rebill_success': value.rebill_success,
        'success': value.success,
        'warning': WarningToJSON(value.warning),
    };
}

