/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelPartnerShippingEstimate
 */
export interface ChannelPartnerShippingEstimate {
    /**
     * The total estimate for this shipping method based on the provided order.
     * @type {number}
     * @memberof ChannelPartnerShippingEstimate
     */
    shipping_handling_total?: number;
    /**
     * The name of the shipping method
     * @type {string}
     * @memberof ChannelPartnerShippingEstimate
     */
    shipping_method?: string;
}

export function ChannelPartnerShippingEstimateFromJSON(json: any): ChannelPartnerShippingEstimate {
    return ChannelPartnerShippingEstimateFromJSONTyped(json, false);
}

export function ChannelPartnerShippingEstimateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelPartnerShippingEstimate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shipping_handling_total': !exists(json, 'shipping_handling_total') ? undefined : json['shipping_handling_total'],
        'shipping_method': !exists(json, 'shipping_method') ? undefined : json['shipping_method'],
    };
}

export function ChannelPartnerShippingEstimateToJSON(value?: ChannelPartnerShippingEstimate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shipping_handling_total': value.shipping_handling_total,
        'shipping_method': value.shipping_method,
    };
}

