/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ChannelPartnerShipToPreference,
    ChannelPartnerShipToPreferenceFromJSON,
    ChannelPartnerShipToPreferenceFromJSONTyped,
    ChannelPartnerShipToPreferenceToJSON,
} from './ChannelPartnerShipToPreference';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface ChannelPartnerShipToPreferenceResponse
 */
export interface ChannelPartnerShipToPreferenceResponse {
    /**
     * 
     * @type {ModelError}
     * @memberof ChannelPartnerShipToPreferenceResponse
     */
    error?: ModelError;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof ChannelPartnerShipToPreferenceResponse
     */
    metadata?: ResponseMetadata;
    /**
     * 
     * @type {ChannelPartnerShipToPreference}
     * @memberof ChannelPartnerShipToPreferenceResponse
     */
    ship_to_preference?: ChannelPartnerShipToPreference;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof ChannelPartnerShipToPreferenceResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Warning}
     * @memberof ChannelPartnerShipToPreferenceResponse
     */
    warning?: Warning;
}



/**
 * Check if a given object implements the ChannelPartnerShipToPreferenceResponse interface.
 */
export function instanceOfChannelPartnerShipToPreferenceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelPartnerShipToPreferenceResponseFromJSON(json: any): ChannelPartnerShipToPreferenceResponse {
    return ChannelPartnerShipToPreferenceResponseFromJSONTyped(json, false);
}

export function ChannelPartnerShipToPreferenceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelPartnerShipToPreferenceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'ship_to_preference': !exists(json, 'ship_to_preference') ? undefined : ChannelPartnerShipToPreferenceFromJSON(json['ship_to_preference']),
        'success': !exists(json, 'success') ? undefined : json['success'],
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function ChannelPartnerShipToPreferenceResponseToJSON(value?: ChannelPartnerShipToPreferenceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ModelErrorToJSON(value.error),
        'metadata': ResponseMetadataToJSON(value.metadata),
        'ship_to_preference': ChannelPartnerShipToPreferenceToJSON(value.ship_to_preference),
        'success': value.success,
        'warning': WarningToJSON(value.warning),
    };
}

