/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Country,
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
} from './Country';

/**
 * 
 * @export
 * @interface CheckoutAllowedCountriesResponse
 */
export interface CheckoutAllowedCountriesResponse {
    /**
     * 
     * @type {Array<Country>}
     * @memberof CheckoutAllowedCountriesResponse
     */
    countries?: Array<Country>;
}

export function CheckoutAllowedCountriesResponseFromJSON(json: any): CheckoutAllowedCountriesResponse {
    return CheckoutAllowedCountriesResponseFromJSONTyped(json, false);
}

export function CheckoutAllowedCountriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutAllowedCountriesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'countries': !exists(json, 'countries') ? undefined : ((json['countries'] as Array<any>).map(CountryFromJSON)),
    };
}

export function CheckoutAllowedCountriesResponseToJSON(value?: CheckoutAllowedCountriesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'countries': value.countries === undefined ? undefined : ((value.countries as Array<any>).map(CountryToJSON)),
    };
}

