/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConversationPbxCallAgent,
    ConversationPbxCallAgentFromJSON,
    ConversationPbxCallAgentFromJSONTyped,
    ConversationPbxCallAgentToJSON,
} from './ConversationPbxCallAgent';
import {
    ConversationPbxCallAiEngagement,
    ConversationPbxCallAiEngagementFromJSON,
    ConversationPbxCallAiEngagementFromJSONTyped,
    ConversationPbxCallAiEngagementToJSON,
} from './ConversationPbxCallAiEngagement';
import {
    ConversationPbxCallCaller,
    ConversationPbxCallCallerFromJSON,
    ConversationPbxCallCallerFromJSONTyped,
    ConversationPbxCallCallerToJSON,
} from './ConversationPbxCallCaller';
import {
    ConversationPbxCallFinancial,
    ConversationPbxCallFinancialFromJSON,
    ConversationPbxCallFinancialFromJSONTyped,
    ConversationPbxCallFinancialToJSON,
} from './ConversationPbxCallFinancial';
import {
    ConversationPbxCallHold,
    ConversationPbxCallHoldFromJSON,
    ConversationPbxCallHoldFromJSONTyped,
    ConversationPbxCallHoldToJSON,
} from './ConversationPbxCallHold';
import {
    ConversationPbxCallRecording,
    ConversationPbxCallRecordingFromJSON,
    ConversationPbxCallRecordingFromJSONTyped,
    ConversationPbxCallRecordingToJSON,
} from './ConversationPbxCallRecording';
import {
    ConversationPbxCallRouting,
    ConversationPbxCallRoutingFromJSON,
    ConversationPbxCallRoutingFromJSONTyped,
    ConversationPbxCallRoutingToJSON,
} from './ConversationPbxCallRouting';
import {
    ConversationPbxCallTimeline,
    ConversationPbxCallTimelineFromJSON,
    ConversationPbxCallTimelineFromJSONTyped,
    ConversationPbxCallTimelineToJSON,
} from './ConversationPbxCallTimeline';
import {
    ConversationPbxCallTransfer,
    ConversationPbxCallTransferFromJSON,
    ConversationPbxCallTransferFromJSONTyped,
    ConversationPbxCallTransferToJSON,
} from './ConversationPbxCallTransfer';

/**
 * 
 * @export
 * @interface ConversationPbxCall
 */
export interface ConversationPbxCall {
    /**
     * Twilio account SID
     * @type {string}
     * @memberof ConversationPbxCall
     */
    account_sid?: string;
    /**
     * List of agents who participated in this call
     * @type {Array<ConversationPbxCallAgent>}
     * @memberof ConversationPbxCall
     */
    agents?: Array<ConversationPbxCallAgent>;
    /**
     * List of AI agent engagements during the call
     * @type {Array<ConversationPbxCallAiEngagement>}
     * @memberof ConversationPbxCall
     */
    ai_agent_engagements?: Array<ConversationPbxCallAiEngagement>;
    /**
     * Twilio call SID for the primary (customer) call leg
     * @type {string}
     * @memberof ConversationPbxCall
     */
    call_sid?: string;
    /**
     * Unique identifier for this call record
     * @type {string}
     * @memberof ConversationPbxCall
     */
    call_uuid?: string;
    /**
     * 
     * @type {ConversationPbxCallCaller}
     * @memberof ConversationPbxCall
     */
    caller?: ConversationPbxCallCaller;
    /**
     * Twilio conference SID if this call used conferencing
     * @type {string}
     * @memberof ConversationPbxCall
     */
    conference_sid?: string;
    /**
     * Timestamp when the call record was created
     * @type {string}
     * @memberof ConversationPbxCall
     */
    created_at_dts?: string;
    /**
     * Customer name associated with this call
     * @type {string}
     * @memberof ConversationPbxCall
     */
    customer_name?: string;
    /**
     * UltraCart customer profile OID if the caller was matched to a customer
     * @type {string}
     * @memberof ConversationPbxCall
     */
    customer_profile_oid?: string;
    /**
     * Call disposition describing how the call ended
     * @type {string}
     * @memberof ConversationPbxCall
     */
    disposition?: string;
    /**
     * Email address of the caller if known
     * @type {string}
     * @memberof ConversationPbxCall
     */
    email?: string;
    /**
     * 
     * @type {ConversationPbxCallFinancial}
     * @memberof ConversationPbxCall
     */
    financial?: ConversationPbxCallFinancial;
    /**
     * List of hold events during the call
     * @type {Array<ConversationPbxCallHold>}
     * @memberof ConversationPbxCall
     */
    holds?: Array<ConversationPbxCallHold>;
    /**
     * Merchant identifier
     * @type {string}
     * @memberof ConversationPbxCall
     */
    merchant_id?: string;
    /**
     * List of all Twilio recording SIDs associated with this call
     * @type {Array<string>}
     * @memberof ConversationPbxCall
     */
    recording_sids?: Array<string>;
    /**
     * List of recordings made during the call
     * @type {Array<ConversationPbxCallRecording>}
     * @memberof ConversationPbxCall
     */
    recordings?: Array<ConversationPbxCallRecording>;
    /**
     * 
     * @type {ConversationPbxCallRouting}
     * @memberof ConversationPbxCall
     */
    routing?: ConversationPbxCallRouting;
    /**
     * Final status of the call
     * @type {string}
     * @memberof ConversationPbxCall
     */
    status?: string;
    /**
     * 
     * @type {ConversationPbxCallTimeline}
     * @memberof ConversationPbxCall
     */
    timeline?: ConversationPbxCallTimeline;
    /**
     * List of transfer events during the call
     * @type {Array<ConversationPbxCallTransfer>}
     * @memberof ConversationPbxCall
     */
    transfers?: Array<ConversationPbxCallTransfer>;
    /**
     * Timestamp when the call record was last updated
     * @type {string}
     * @memberof ConversationPbxCall
     */
    updated_at_dts?: string;
}



/**
 * Check if a given object implements the ConversationPbxCall interface.
 */
export function instanceOfConversationPbxCall(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConversationPbxCallFromJSON(json: any): ConversationPbxCall {
    return ConversationPbxCallFromJSONTyped(json, false);
}

export function ConversationPbxCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationPbxCall {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'account_sid': !exists(json, 'account_sid') ? undefined : json['account_sid'],
        'agents': !exists(json, 'agents') ? undefined : ((json['agents'] as Array<any>).map(ConversationPbxCallAgentFromJSON)),
        'ai_agent_engagements': !exists(json, 'ai_agent_engagements') ? undefined : ((json['ai_agent_engagements'] as Array<any>).map(ConversationPbxCallAiEngagementFromJSON)),
        'call_sid': !exists(json, 'call_sid') ? undefined : json['call_sid'],
        'call_uuid': !exists(json, 'call_uuid') ? undefined : json['call_uuid'],
        'caller': !exists(json, 'caller') ? undefined : ConversationPbxCallCallerFromJSON(json['caller']),
        'conference_sid': !exists(json, 'conference_sid') ? undefined : json['conference_sid'],
        'created_at_dts': !exists(json, 'created_at_dts') ? undefined : json['created_at_dts'],
        'customer_name': !exists(json, 'customer_name') ? undefined : json['customer_name'],
        'customer_profile_oid': !exists(json, 'customer_profile_oid') ? undefined : json['customer_profile_oid'],
        'disposition': !exists(json, 'disposition') ? undefined : json['disposition'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'financial': !exists(json, 'financial') ? undefined : ConversationPbxCallFinancialFromJSON(json['financial']),
        'holds': !exists(json, 'holds') ? undefined : ((json['holds'] as Array<any>).map(ConversationPbxCallHoldFromJSON)),
        'merchant_id': !exists(json, 'merchant_id') ? undefined : json['merchant_id'],
        'recording_sids': !exists(json, 'recording_sids') ? undefined : json['recording_sids'],
        'recordings': !exists(json, 'recordings') ? undefined : ((json['recordings'] as Array<any>).map(ConversationPbxCallRecordingFromJSON)),
        'routing': !exists(json, 'routing') ? undefined : ConversationPbxCallRoutingFromJSON(json['routing']),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'timeline': !exists(json, 'timeline') ? undefined : ConversationPbxCallTimelineFromJSON(json['timeline']),
        'transfers': !exists(json, 'transfers') ? undefined : ((json['transfers'] as Array<any>).map(ConversationPbxCallTransferFromJSON)),
        'updated_at_dts': !exists(json, 'updated_at_dts') ? undefined : json['updated_at_dts'],
    };
}

export function ConversationPbxCallToJSON(value?: ConversationPbxCall | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_sid': value.account_sid,
        'agents': value.agents === undefined ? undefined : ((value.agents as Array<any>).map(ConversationPbxCallAgentToJSON)),
        'ai_agent_engagements': value.ai_agent_engagements === undefined ? undefined : ((value.ai_agent_engagements as Array<any>).map(ConversationPbxCallAiEngagementToJSON)),
        'call_sid': value.call_sid,
        'call_uuid': value.call_uuid,
        'caller': ConversationPbxCallCallerToJSON(value.caller),
        'conference_sid': value.conference_sid,
        'created_at_dts': value.created_at_dts,
        'customer_name': value.customer_name,
        'customer_profile_oid': value.customer_profile_oid,
        'disposition': value.disposition,
        'email': value.email,
        'financial': ConversationPbxCallFinancialToJSON(value.financial),
        'holds': value.holds === undefined ? undefined : ((value.holds as Array<any>).map(ConversationPbxCallHoldToJSON)),
        'merchant_id': value.merchant_id,
        'recording_sids': value.recording_sids,
        'recordings': value.recordings === undefined ? undefined : ((value.recordings as Array<any>).map(ConversationPbxCallRecordingToJSON)),
        'routing': ConversationPbxCallRoutingToJSON(value.routing),
        'status': value.status,
        'timeline': ConversationPbxCallTimelineToJSON(value.timeline),
        'transfers': value.transfers === undefined ? undefined : ((value.transfers as Array<any>).map(ConversationPbxCallTransferToJSON)),
        'updated_at_dts': value.updated_at_dts,
    };
}

