/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationAgentStatusRollupSearchRequest
 */
export interface ConversationAgentStatusRollupSearchRequest {
    /**
     * Optional agent_user_id filter
     * @type {string}
     * @memberof ConversationAgentStatusRollupSearchRequest
     */
    agent_user_id?: string;
    /**
     * Optional channel filter
     * @type {string}
     * @memberof ConversationAgentStatusRollupSearchRequest
     */
    channel?: ConversationAgentStatusRollupSearchRequestChannelEnum;
    /**
     * Date range end (YYYY-MM-DD)
     * @type {string}
     * @memberof ConversationAgentStatusRollupSearchRequest
     */
    date_end?: string;
    /**
     * Date range start (YYYY-MM-DD)
     * @type {string}
     * @memberof ConversationAgentStatusRollupSearchRequest
     */
    date_start?: string;
}



/**
 * @export
 */
export const ConversationAgentStatusRollupSearchRequestChannelEnum = {
    Pbx: 'pbx',
    Chat: 'chat'
} as const;
export type ConversationAgentStatusRollupSearchRequestChannelEnum = typeof ConversationAgentStatusRollupSearchRequestChannelEnum[keyof typeof ConversationAgentStatusRollupSearchRequestChannelEnum];


/**
 * Check if a given object implements the ConversationAgentStatusRollupSearchRequest interface.
 */
export function instanceOfConversationAgentStatusRollupSearchRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConversationAgentStatusRollupSearchRequestFromJSON(json: any): ConversationAgentStatusRollupSearchRequest {
    return ConversationAgentStatusRollupSearchRequestFromJSONTyped(json, false);
}

export function ConversationAgentStatusRollupSearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationAgentStatusRollupSearchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agent_user_id': !exists(json, 'agent_user_id') ? undefined : json['agent_user_id'],
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
        'date_end': !exists(json, 'date_end') ? undefined : json['date_end'],
        'date_start': !exists(json, 'date_start') ? undefined : json['date_start'],
    };
}

export function ConversationAgentStatusRollupSearchRequestToJSON(value?: ConversationAgentStatusRollupSearchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agent_user_id': value.agent_user_id,
        'channel': value.channel,
        'date_end': value.date_end,
        'date_start': value.date_start,
    };
}

