/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationPbxCallAiToolCall
 */
export interface ConversationPbxCallAiToolCall {
    /**
     * Timestamp when the tool was called
     * @type {string}
     * @memberof ConversationPbxCallAiToolCall
     */
    called_at_dts?: string;
    /**
     * Timestamp when the tool call completed
     * @type {string}
     * @memberof ConversationPbxCallAiToolCall
     */
    completed_at_dts?: string;
    /**
     * Duration of the tool call in milliseconds
     * @type {number}
     * @memberof ConversationPbxCallAiToolCall
     */
    duration_ms?: number;
    /**
     * Error message if the tool call failed
     * @type {string}
     * @memberof ConversationPbxCallAiToolCall
     */
    error_message?: string;
    /**
     * Parameters passed to the tool (structure varies by tool)
     * @type {object}
     * @memberof ConversationPbxCallAiToolCall
     */
    parameters?: object;
    /**
     * Result returned by the tool (structure varies by tool)
     * @type {object}
     * @memberof ConversationPbxCallAiToolCall
     */
    result?: object;
    /**
     * Whether the tool call succeeded
     * @type {boolean}
     * @memberof ConversationPbxCallAiToolCall
     */
    success?: boolean;
    /**
     * Unique identifier for this tool call
     * @type {string}
     * @memberof ConversationPbxCallAiToolCall
     */
    tool_call_uuid?: string;
    /**
     * Name of the tool that was called
     * @type {string}
     * @memberof ConversationPbxCallAiToolCall
     */
    tool_name?: string;
}



/**
 * Check if a given object implements the ConversationPbxCallAiToolCall interface.
 */
export function instanceOfConversationPbxCallAiToolCall(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConversationPbxCallAiToolCallFromJSON(json: any): ConversationPbxCallAiToolCall {
    return ConversationPbxCallAiToolCallFromJSONTyped(json, false);
}

export function ConversationPbxCallAiToolCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationPbxCallAiToolCall {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'called_at_dts': !exists(json, 'called_at_dts') ? undefined : json['called_at_dts'],
        'completed_at_dts': !exists(json, 'completed_at_dts') ? undefined : json['completed_at_dts'],
        'duration_ms': !exists(json, 'duration_ms') ? undefined : json['duration_ms'],
        'error_message': !exists(json, 'error_message') ? undefined : json['error_message'],
        'parameters': !exists(json, 'parameters') ? undefined : json['parameters'],
        'result': !exists(json, 'result') ? undefined : json['result'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'tool_call_uuid': !exists(json, 'tool_call_uuid') ? undefined : json['tool_call_uuid'],
        'tool_name': !exists(json, 'tool_name') ? undefined : json['tool_name'],
    };
}

export function ConversationPbxCallAiToolCallToJSON(value?: ConversationPbxCallAiToolCall | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'called_at_dts': value.called_at_dts,
        'completed_at_dts': value.completed_at_dts,
        'duration_ms': value.duration_ms,
        'error_message': value.error_message,
        'parameters': value.parameters,
        'result': value.result,
        'success': value.success,
        'tool_call_uuid': value.tool_call_uuid,
        'tool_name': value.tool_name,
    };
}

