/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationDepartmentMember
 */
export interface ConversationDepartmentMember {
    /**
     * 
     * @type {boolean}
     * @memberof ConversationDepartmentMember
     */
    ai?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationDepartmentMember
     */
    member?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConversationDepartmentMember
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ConversationDepartmentMember
     */
    user_id?: number;
}



/**
 * Check if a given object implements the ConversationDepartmentMember interface.
 */
export function instanceOfConversationDepartmentMember(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConversationDepartmentMemberFromJSON(json: any): ConversationDepartmentMember {
    return ConversationDepartmentMemberFromJSONTyped(json, false);
}

export function ConversationDepartmentMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationDepartmentMember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ai': !exists(json, 'ai') ? undefined : json['ai'],
        'member': !exists(json, 'member') ? undefined : json['member'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'user_id': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function ConversationDepartmentMemberToJSON(value?: ConversationDepartmentMember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ai': value.ai,
        'member': value.member,
        'name': value.name,
        'user_id': value.user_id,
    };
}

