/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationMessageTranslation
 */
export interface ConversationMessageTranslation {
    /**
     * 
     * @type {string}
     * @memberof ConversationMessageTranslation
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMessageTranslation
     */
    language_iso_code?: string;
}

// Define the constant array of keys
const MY_INTERFACE_KEYS: (keyof ConversationMessageTranslation)[] = ["body", "language_iso_code"];

// Exported function to check for excess properties
export function hasExcessProperties(obj: any): boolean {
  const objKeys = Object.keys(obj);
  return objKeys.some(key => !MY_INTERFACE_KEYS.includes(key as keyof MyInterface));
}



/**
 * Check if a given object implements the ConversationMessageTranslation interface.
 */
export function instanceOfConversationMessageTranslation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ConversationMessageTranslationFromJSON(json: any): ConversationMessageTranslation {
    return ConversationMessageTranslationFromJSONTyped(json, false);
}

export function ConversationMessageTranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationMessageTranslation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': !exists(json, 'body') ? undefined : json['body'],
        'language_iso_code': !exists(json, 'language_iso_code') ? undefined : json['language_iso_code'],
    };
}

export function ConversationMessageTranslationToJSON(value?: ConversationMessageTranslation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
        'language_iso_code': value.language_iso_code,
    };
}

