/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CouponPercentOffItemsWithItemsPurchase
 */
export interface CouponPercentOffItemsWithItemsPurchase {
    /**
     * The percentage of subtotal discount
     * @type {number}
     * @memberof CouponPercentOffItemsWithItemsPurchase
     */
    discount_percent?: number;
    /**
     * An optional list of item tags which will receive a discount of one of the required purchased items is purchased.
     * @type {Array<string>}
     * @memberof CouponPercentOffItemsWithItemsPurchase
     */
    item_tags?: Array<string>;
    /**
     * A list of items which will receive a discount if one of the required purchase items is purchased.
     * @type {Array<string>}
     * @memberof CouponPercentOffItemsWithItemsPurchase
     */
    items?: Array<string>;
    /**
     * The (optional) maximum quantity of discounted items.
     * @type {number}
     * @memberof CouponPercentOffItemsWithItemsPurchase
     */
    limit?: number;
    /**
     * Required items (at least one from the list) that must be purchased for coupon to be valid
     * @type {Array<string>}
     * @memberof CouponPercentOffItemsWithItemsPurchase
     */
    required_purchase_items?: Array<string>;
    /**
     * An optional list of item tags which are required to be purchased.
     * @type {Array<string>}
     * @memberof CouponPercentOffItemsWithItemsPurchase
     */
    required_purchase_items_tags?: Array<string>;
}



/**
 * Check if a given object implements the CouponPercentOffItemsWithItemsPurchase interface.
 */
export function instanceOfCouponPercentOffItemsWithItemsPurchase(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CouponPercentOffItemsWithItemsPurchaseFromJSON(json: any): CouponPercentOffItemsWithItemsPurchase {
    return CouponPercentOffItemsWithItemsPurchaseFromJSONTyped(json, false);
}

export function CouponPercentOffItemsWithItemsPurchaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponPercentOffItemsWithItemsPurchase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discount_percent': !exists(json, 'discount_percent') ? undefined : json['discount_percent'],
        'item_tags': !exists(json, 'item_tags') ? undefined : json['item_tags'],
        'items': !exists(json, 'items') ? undefined : json['items'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'required_purchase_items': !exists(json, 'required_purchase_items') ? undefined : json['required_purchase_items'],
        'required_purchase_items_tags': !exists(json, 'required_purchase_items_tags') ? undefined : json['required_purchase_items_tags'],
    };
}

export function CouponPercentOffItemsWithItemsPurchaseToJSON(value?: CouponPercentOffItemsWithItemsPurchase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discount_percent': value.discount_percent,
        'item_tags': value.item_tags,
        'items': value.items,
        'limit': value.limit,
        'required_purchase_items': value.required_purchase_items,
        'required_purchase_items_tags': value.required_purchase_items_tags,
    };
}

