/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CouponPercentOffSubtotal
 */
export interface CouponPercentOffSubtotal {
    /**
     * The percentage of subtotal discount
     * @type {number}
     * @memberof CouponPercentOffSubtotal
     */
    discount_percent?: number;
}

export function CouponPercentOffSubtotalFromJSON(json: any): CouponPercentOffSubtotal {
    return CouponPercentOffSubtotalFromJSONTyped(json, false);
}

export function CouponPercentOffSubtotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponPercentOffSubtotal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discount_percent': !exists(json, 'discount_percent') ? undefined : json['discount_percent'],
    };
}

export function CouponPercentOffSubtotalToJSON(value?: CouponPercentOffSubtotal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discount_percent': value.discount_percent,
    };
}

