/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CouponTierQuantityAmount
 */
export interface CouponTierQuantityAmount {
    /**
     * The amount of discount per item.
     * @type {number}
     * @memberof CouponTierQuantityAmount
     */
    discount_amount?: number;
    /**
     * The quantity of item purchased (in units)
     * @type {number}
     * @memberof CouponTierQuantityAmount
     */
    item_quantity?: number;
    /**
     * Quickbooks accounting code.
     * @type {string}
     * @memberof CouponTierQuantityAmount
     */
    quickbooks_code?: string;
}

export function CouponTierQuantityAmountFromJSON(json: any): CouponTierQuantityAmount {
    return CouponTierQuantityAmountFromJSONTyped(json, false);
}

export function CouponTierQuantityAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponTierQuantityAmount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discount_amount': !exists(json, 'discount_amount') ? undefined : json['discount_amount'],
        'item_quantity': !exists(json, 'item_quantity') ? undefined : json['item_quantity'],
        'quickbooks_code': !exists(json, 'quickbooks_code') ? undefined : json['quickbooks_code'],
    };
}

export function CouponTierQuantityAmountToJSON(value?: CouponTierQuantityAmount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discount_amount': value.discount_amount,
        'item_quantity': value.item_quantity,
        'quickbooks_code': value.quickbooks_code,
    };
}

