/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomDashboardPageReport,
    CustomDashboardPageReportFromJSON,
    CustomDashboardPageReportFromJSONTyped,
    CustomDashboardPageReportToJSON,
} from './CustomDashboardPageReport';

/**
 * 
 * @export
 * @interface CustomDashboardPage
 */
export interface CustomDashboardPage {
    /**
     * 
     * @type {number}
     * @memberof CustomDashboardPage
     */
    page_height_inches?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomDashboardPage
     */
    page_width_inches?: number;
    /**
     * 
     * @type {Array<CustomDashboardPageReport>}
     * @memberof CustomDashboardPage
     */
    reports?: Array<CustomDashboardPageReport>;
}



/**
 * Check if a given object implements the CustomDashboardPage interface.
 */
export function instanceOfCustomDashboardPage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomDashboardPageFromJSON(json: any): CustomDashboardPage {
    return CustomDashboardPageFromJSONTyped(json, false);
}

export function CustomDashboardPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDashboardPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page_height_inches': !exists(json, 'page_height_inches') ? undefined : json['page_height_inches'],
        'page_width_inches': !exists(json, 'page_width_inches') ? undefined : json['page_width_inches'],
        'reports': !exists(json, 'reports') ? undefined : ((json['reports'] as Array<any>).map(CustomDashboardPageReportFromJSON)),
    };
}

export function CustomDashboardPageToJSON(value?: CustomDashboardPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page_height_inches': value.page_height_inches,
        'page_width_inches': value.page_width_inches,
        'reports': value.reports === undefined ? undefined : ((value.reports as Array<any>).map(CustomDashboardPageReportToJSON)),
    };
}

