/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerAttachment
 */
export interface CustomerAttachment {
    /**
     * Attachment identifier
     * @type {number}
     * @memberof CustomerAttachment
     */
    customer_profile_attachment_oid?: number;
    /**
     * Description
     * @type {string}
     * @memberof CustomerAttachment
     */
    description?: string;
    /**
     * File name
     * @type {string}
     * @memberof CustomerAttachment
     */
    file_name?: string;
    /**
     * Mime typoe
     * @type {string}
     * @memberof CustomerAttachment
     */
    mime_type?: string;
    /**
     * Upload date/time
     * @type {string}
     * @memberof CustomerAttachment
     */
    upload_dts?: string;
}

export function CustomerAttachmentFromJSON(json: any): CustomerAttachment {
    return CustomerAttachmentFromJSONTyped(json, false);
}

export function CustomerAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerAttachment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer_profile_attachment_oid': !exists(json, 'customer_profile_attachment_oid') ? undefined : json['customer_profile_attachment_oid'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'file_name': !exists(json, 'file_name') ? undefined : json['file_name'],
        'mime_type': !exists(json, 'mime_type') ? undefined : json['mime_type'],
        'upload_dts': !exists(json, 'upload_dts') ? undefined : json['upload_dts'],
    };
}

export function CustomerAttachmentToJSON(value?: CustomerAttachment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer_profile_attachment_oid': value.customer_profile_attachment_oid,
        'description': value.description,
        'file_name': value.file_name,
        'mime_type': value.mime_type,
        'upload_dts': value.upload_dts,
    };
}

