/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmailSuppressionSurfaces,
    EmailSuppressionSurfacesFromJSON,
    EmailSuppressionSurfacesFromJSONTyped,
    EmailSuppressionSurfacesToJSON,
} from './EmailSuppressionSurfaces';

/**
 * 
 * @export
 * @interface CustomerEmailSuppressionResult
 */
export interface CustomerEmailSuppressionResult {
    /**
     * True only if this call actually removed bounce suppression.  Bounce has no per-customer flag, so there is no corresponding state field.
     * @type {boolean}
     * @memberof CustomerEmailSuppressionResult
     */
    bounce_cleared?: boolean;
    /**
     * The customer profile oid that was operated on
     * @type {number}
     * @memberof CustomerEmailSuppressionResult
     */
    customer_profile_oid?: number;
    /**
     * The email address that was operated on
     * @type {string}
     * @memberof CustomerEmailSuppressionResult
     */
    email?: string;
    /**
     * True only if every requested suppression surface was successfully cleared.  When false, see esp_warning -- the profile was still modified.
     * @type {boolean}
     * @memberof CustomerEmailSuppressionResult
     */
    esp_suppression_removed?: boolean;
    /**
     * Human readable explanation when esp_suppression_removed is false.  Suitable for display to a support agent.
     * @type {string}
     * @memberof CustomerEmailSuppressionResult
     */
    esp_warning?: string;
    /**
     * True only if this call actually changed the global unsubscribe flag.  False if it was already clear.
     * @type {boolean}
     * @memberof CustomerEmailSuppressionResult
     */
    global_unsubscribe_cleared?: boolean;
    /**
     * Global unsubscribe state AFTER this call
     * @type {boolean}
     * @memberof CustomerEmailSuppressionResult
     */
    global_unsubscribed?: boolean;
    /**
     * Global unsubscribe timestamp after this call.  Nulled when cleared; the prior value is retained on the audit record.
     * @type {string}
     * @memberof CustomerEmailSuppressionResult
     */
    global_unsubscribed_dts?: string;
    /**
     * Spam complaint state AFTER this call
     * @type {boolean}
     * @memberof CustomerEmailSuppressionResult
     */
    spam_complaint?: boolean;
    /**
     * True only if this call actually changed the spam complaint flag.  False if it was already clear.
     * @type {boolean}
     * @memberof CustomerEmailSuppressionResult
     */
    spam_complaint_cleared?: boolean;
    /**
     * Spam complaint timestamp after this call.  Nulled when cleared; the prior value is retained on the audit record.
     * @type {string}
     * @memberof CustomerEmailSuppressionResult
     */
    spam_complaint_dts?: string;
    /**
     * 
     * @type {EmailSuppressionSurfaces}
     * @memberof CustomerEmailSuppressionResult
     */
    suppression_surfaces?: EmailSuppressionSurfaces;
}



/**
 * Check if a given object implements the CustomerEmailSuppressionResult interface.
 */
export function instanceOfCustomerEmailSuppressionResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomerEmailSuppressionResultFromJSON(json: any): CustomerEmailSuppressionResult {
    return CustomerEmailSuppressionResultFromJSONTyped(json, false);
}

export function CustomerEmailSuppressionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerEmailSuppressionResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bounce_cleared': !exists(json, 'bounce_cleared') ? undefined : json['bounce_cleared'],
        'customer_profile_oid': !exists(json, 'customer_profile_oid') ? undefined : json['customer_profile_oid'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'esp_suppression_removed': !exists(json, 'esp_suppression_removed') ? undefined : json['esp_suppression_removed'],
        'esp_warning': !exists(json, 'esp_warning') ? undefined : json['esp_warning'],
        'global_unsubscribe_cleared': !exists(json, 'global_unsubscribe_cleared') ? undefined : json['global_unsubscribe_cleared'],
        'global_unsubscribed': !exists(json, 'global_unsubscribed') ? undefined : json['global_unsubscribed'],
        'global_unsubscribed_dts': !exists(json, 'global_unsubscribed_dts') ? undefined : json['global_unsubscribed_dts'],
        'spam_complaint': !exists(json, 'spam_complaint') ? undefined : json['spam_complaint'],
        'spam_complaint_cleared': !exists(json, 'spam_complaint_cleared') ? undefined : json['spam_complaint_cleared'],
        'spam_complaint_dts': !exists(json, 'spam_complaint_dts') ? undefined : json['spam_complaint_dts'],
        'suppression_surfaces': !exists(json, 'suppression_surfaces') ? undefined : EmailSuppressionSurfacesFromJSON(json['suppression_surfaces']),
    };
}

export function CustomerEmailSuppressionResultToJSON(value?: CustomerEmailSuppressionResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bounce_cleared': value.bounce_cleared,
        'customer_profile_oid': value.customer_profile_oid,
        'email': value.email,
        'esp_suppression_removed': value.esp_suppression_removed,
        'esp_warning': value.esp_warning,
        'global_unsubscribe_cleared': value.global_unsubscribe_cleared,
        'global_unsubscribed': value.global_unsubscribed,
        'global_unsubscribed_dts': value.global_unsubscribed_dts,
        'spam_complaint': value.spam_complaint,
        'spam_complaint_cleared': value.spam_complaint_cleared,
        'spam_complaint_dts': value.spam_complaint_dts,
        'suppression_surfaces': EmailSuppressionSurfacesToJSON(value.suppression_surfaces),
    };
}

