/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmailDispatchLog,
    EmailDispatchLogFromJSON,
    EmailDispatchLogFromJSONTyped,
    EmailDispatchLogToJSON,
} from './EmailDispatchLog';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface EmailDispatchLogsResponse
 */
export interface EmailDispatchLogsResponse {
    /**
     * Dispatch log rows on this page
     * @type {Array<EmailDispatchLog>}
     * @memberof EmailDispatchLogsResponse
     */
    dispatch_logs?: Array<EmailDispatchLog>;
    /**
     * 
     * @type {ModelError}
     * @memberof EmailDispatchLogsResponse
     */
    error?: ModelError;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof EmailDispatchLogsResponse
     */
    metadata?: ResponseMetadata;
    /**
     * True when another page exists after this one
     * @type {boolean}
     * @memberof EmailDispatchLogsResponse
     */
    more?: boolean;
    /**
     * Page number (one based)
     * @type {number}
     * @memberof EmailDispatchLogsResponse
     */
    page_number?: number;
    /**
     * Number of records per page
     * @type {number}
     * @memberof EmailDispatchLogsResponse
     */
    page_size?: number;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof EmailDispatchLogsResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Warning}
     * @memberof EmailDispatchLogsResponse
     */
    warning?: Warning;
}



/**
 * Check if a given object implements the EmailDispatchLogsResponse interface.
 */
export function instanceOfEmailDispatchLogsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailDispatchLogsResponseFromJSON(json: any): EmailDispatchLogsResponse {
    return EmailDispatchLogsResponseFromJSONTyped(json, false);
}

export function EmailDispatchLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDispatchLogsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dispatch_logs': !exists(json, 'dispatch_logs') ? undefined : ((json['dispatch_logs'] as Array<any>).map(EmailDispatchLogFromJSON)),
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'more': !exists(json, 'more') ? undefined : json['more'],
        'page_number': !exists(json, 'page_number') ? undefined : json['page_number'],
        'page_size': !exists(json, 'page_size') ? undefined : json['page_size'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function EmailDispatchLogsResponseToJSON(value?: EmailDispatchLogsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dispatch_logs': value.dispatch_logs === undefined ? undefined : ((value.dispatch_logs as Array<any>).map(EmailDispatchLogToJSON)),
        'error': ModelErrorToJSON(value.error),
        'metadata': ResponseMetadataToJSON(value.metadata),
        'more': value.more,
        'page_number': value.page_number,
        'page_size': value.page_size,
        'success': value.success,
        'warning': WarningToJSON(value.warning),
    };
}

