/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailHistogramPropertyValuesResponse
 */
export interface EmailHistogramPropertyValuesResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof EmailHistogramPropertyValuesResponse
     */
    property_values?: Array<string>;
}

// Define the constant array of keys
const MY_INTERFACE_KEYS: (keyof EmailHistogramPropertyValuesResponse)[] = ["property_values"];

// Exported function to check for excess properties
export function hasExcessProperties(obj: any): boolean {
  const objKeys = Object.keys(obj);
  return objKeys.some(key => !MY_INTERFACE_KEYS.includes(key as keyof MyInterface));
}



/**
 * Check if a given object implements the EmailHistogramPropertyValuesResponse interface.
 */
export function instanceOfEmailHistogramPropertyValuesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailHistogramPropertyValuesResponseFromJSON(json: any): EmailHistogramPropertyValuesResponse {
    return EmailHistogramPropertyValuesResponseFromJSONTyped(json, false);
}

export function EmailHistogramPropertyValuesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailHistogramPropertyValuesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'property_values': !exists(json, 'property_values') ? undefined : json['property_values'],
    };
}

export function EmailHistogramPropertyValuesResponseToJSON(value?: EmailHistogramPropertyValuesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'property_values': value.property_values,
    };
}

