/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmailTemplate,
    EmailTemplateFromJSON,
    EmailTemplateFromJSONTyped,
    EmailTemplateToJSON,
} from './EmailTemplate';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface EmailTemplatesResponse
 */
export interface EmailTemplatesResponse {
    /**
     * 
     * @type {ModelError}
     * @memberof EmailTemplatesResponse
     */
    error?: ModelError;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof EmailTemplatesResponse
     */
    metadata?: ResponseMetadata;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof EmailTemplatesResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Array<EmailTemplate>}
     * @memberof EmailTemplatesResponse
     */
    templates?: Array<EmailTemplate>;
    /**
     * 
     * @type {Warning}
     * @memberof EmailTemplatesResponse
     */
    warning?: Warning;
}

// Define the constant array of keys
const MY_INTERFACE_KEYS: (keyof EmailTemplatesResponse)[] = ["error", "metadata", "success", "templates", "warning"];

// Exported function to check for excess properties
export function hasExcessProperties(obj: any): boolean {
  const objKeys = Object.keys(obj);
  return objKeys.some(key => !MY_INTERFACE_KEYS.includes(key as keyof MyInterface));
}



/**
 * Check if a given object implements the EmailTemplatesResponse interface.
 */
export function instanceOfEmailTemplatesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailTemplatesResponseFromJSON(json: any): EmailTemplatesResponse {
    return EmailTemplatesResponseFromJSONTyped(json, false);
}

export function EmailTemplatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailTemplatesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'success': !exists(json, 'success') ? undefined : json['success'],
        'templates': !exists(json, 'templates') ? undefined : ((json['templates'] as Array<any>).map(EmailTemplateFromJSON)),
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function EmailTemplatesResponseToJSON(value?: EmailTemplatesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ModelErrorToJSON(value.error),
        'metadata': ResponseMetadataToJSON(value.metadata),
        'success': value.success,
        'templates': value.templates === undefined ? undefined : ((value.templates as Array<any>).map(EmailTemplateToJSON)),
        'warning': WarningToJSON(value.warning),
    };
}

