/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface EmailCommseqEnrollmentResponse
 */
export interface EmailCommseqEnrollmentResponse {
    /**
     * True if the customer was already enrolled and therefore not enrolled again
     * @type {boolean}
     * @memberof EmailCommseqEnrollmentResponse
     */
    already_enrolled?: boolean;
    /**
     * True if the customer was newly enrolled into the sequence
     * @type {boolean}
     * @memberof EmailCommseqEnrollmentResponse
     */
    enrolled?: boolean;
    /**
     * 
     * @type {ModelError}
     * @memberof EmailCommseqEnrollmentResponse
     */
    error?: ModelError;
    /**
     * The resolved ESP customer UUID for the enrolled email
     * @type {string}
     * @memberof EmailCommseqEnrollmentResponse
     */
    esp_customer_uuid?: string;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof EmailCommseqEnrollmentResponse
     */
    metadata?: ResponseMetadata;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof EmailCommseqEnrollmentResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Warning}
     * @memberof EmailCommseqEnrollmentResponse
     */
    warning?: Warning;
}



/**
 * Check if a given object implements the EmailCommseqEnrollmentResponse interface.
 */
export function instanceOfEmailCommseqEnrollmentResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailCommseqEnrollmentResponseFromJSON(json: any): EmailCommseqEnrollmentResponse {
    return EmailCommseqEnrollmentResponseFromJSONTyped(json, false);
}

export function EmailCommseqEnrollmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailCommseqEnrollmentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'already_enrolled': !exists(json, 'already_enrolled') ? undefined : json['already_enrolled'],
        'enrolled': !exists(json, 'enrolled') ? undefined : json['enrolled'],
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'esp_customer_uuid': !exists(json, 'esp_customer_uuid') ? undefined : json['esp_customer_uuid'],
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'success': !exists(json, 'success') ? undefined : json['success'],
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function EmailCommseqEnrollmentResponseToJSON(value?: EmailCommseqEnrollmentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'already_enrolled': value.already_enrolled,
        'enrolled': value.enrolled,
        'error': ModelErrorToJSON(value.error),
        'esp_customer_uuid': value.esp_customer_uuid,
        'metadata': ResponseMetadataToJSON(value.metadata),
        'success': value.success,
        'warning': WarningToJSON(value.warning),
    };
}

