/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmailCommseqEmailReviewStatus,
    EmailCommseqEmailReviewStatusFromJSON,
    EmailCommseqEmailReviewStatusFromJSONTyped,
    EmailCommseqEmailReviewStatusToJSON,
} from './EmailCommseqEmailReviewStatus';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface EmailCommseqEmailReviewStatusResponse
 */
export interface EmailCommseqEmailReviewStatusResponse {
    /**
     * 
     * @type {ModelError}
     * @memberof EmailCommseqEmailReviewStatusResponse
     */
    error?: ModelError;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof EmailCommseqEmailReviewStatusResponse
     */
    metadata?: ResponseMetadata;
    /**
     * 
     * @type {EmailCommseqEmailReviewStatus}
     * @memberof EmailCommseqEmailReviewStatusResponse
     */
    review_status?: EmailCommseqEmailReviewStatus;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof EmailCommseqEmailReviewStatusResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Warning}
     * @memberof EmailCommseqEmailReviewStatusResponse
     */
    warning?: Warning;
}



/**
 * Check if a given object implements the EmailCommseqEmailReviewStatusResponse interface.
 */
export function instanceOfEmailCommseqEmailReviewStatusResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailCommseqEmailReviewStatusResponseFromJSON(json: any): EmailCommseqEmailReviewStatusResponse {
    return EmailCommseqEmailReviewStatusResponseFromJSONTyped(json, false);
}

export function EmailCommseqEmailReviewStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailCommseqEmailReviewStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'review_status': !exists(json, 'review_status') ? undefined : EmailCommseqEmailReviewStatusFromJSON(json['review_status']),
        'success': !exists(json, 'success') ? undefined : json['success'],
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function EmailCommseqEmailReviewStatusResponseToJSON(value?: EmailCommseqEmailReviewStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ModelErrorToJSON(value.error),
        'metadata': ResponseMetadataToJSON(value.metadata),
        'review_status': EmailCommseqEmailReviewStatusToJSON(value.review_status),
        'success': value.success,
        'warning': WarningToJSON(value.warning),
    };
}

