/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmailSmsStat,
    EmailSmsStatFromJSON,
    EmailSmsStatFromJSONTyped,
    EmailSmsStatToJSON,
} from './EmailSmsStat';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface EmailStatSmsSummaryResponse
 */
export interface EmailStatSmsSummaryResponse {
    /**
     * 
     * @type {ModelError}
     * @memberof EmailStatSmsSummaryResponse
     */
    error?: ModelError;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof EmailStatSmsSummaryResponse
     */
    metadata?: ResponseMetadata;
    /**
     * 
     * @type {Array<EmailSmsStat>}
     * @memberof EmailStatSmsSummaryResponse
     */
    stats?: Array<EmailSmsStat>;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof EmailStatSmsSummaryResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Warning}
     * @memberof EmailStatSmsSummaryResponse
     */
    warning?: Warning;
}



/**
 * Check if a given object implements the EmailStatSmsSummaryResponse interface.
 */
export function instanceOfEmailStatSmsSummaryResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailStatSmsSummaryResponseFromJSON(json: any): EmailStatSmsSummaryResponse {
    return EmailStatSmsSummaryResponseFromJSONTyped(json, false);
}

export function EmailStatSmsSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailStatSmsSummaryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'stats': !exists(json, 'stats') ? undefined : ((json['stats'] as Array<any>).map(EmailSmsStatFromJSON)),
        'success': !exists(json, 'success') ? undefined : json['success'],
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function EmailStatSmsSummaryResponseToJSON(value?: EmailStatSmsSummaryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ModelErrorToJSON(value.error),
        'metadata': ResponseMetadataToJSON(value.metadata),
        'stats': value.stats === undefined ? undefined : ((value.stats as Array<any>).map(EmailSmsStatToJSON)),
        'success': value.success,
        'warning': WarningToJSON(value.warning),
    };
}

