/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GiftCertificate,
    GiftCertificateFromJSON,
    GiftCertificateFromJSONTyped,
    GiftCertificateToJSON,
} from './GiftCertificate';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface GiftCertificateResponse
 */
export interface GiftCertificateResponse {
    /**
     * 
     * @type {ModelError}
     * @memberof GiftCertificateResponse
     */
    error?: ModelError;
    /**
     * 
     * @type {GiftCertificate}
     * @memberof GiftCertificateResponse
     */
    gift_certificate?: GiftCertificate;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof GiftCertificateResponse
     */
    metadata?: ResponseMetadata;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof GiftCertificateResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Warning}
     * @memberof GiftCertificateResponse
     */
    warning?: Warning;
}



/**
 * Check if a given object implements the GiftCertificateResponse interface.
 */
export function instanceOfGiftCertificateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GiftCertificateResponseFromJSON(json: any): GiftCertificateResponse {
    return GiftCertificateResponseFromJSONTyped(json, false);
}

export function GiftCertificateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GiftCertificateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'gift_certificate': !exists(json, 'gift_certificate') ? undefined : GiftCertificateFromJSON(json['gift_certificate']),
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'success': !exists(json, 'success') ? undefined : json['success'],
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function GiftCertificateResponseToJSON(value?: GiftCertificateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ModelErrorToJSON(value.error),
        'gift_certificate': GiftCertificateToJSON(value.gift_certificate),
        'metadata': ResponseMetadataToJSON(value.metadata),
        'success': value.success,
        'warning': WarningToJSON(value.warning),
    };
}

