/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemAmember
 */
export interface ItemAmember {
    /**
     * The number of days that the customer should be given access to the item
     * @type {number}
     * @memberof ItemAmember
     */
    amember_payment_duration_days?: number;
    /**
     * A-member product id give customer access to when they purchase this item
     * @type {string}
     * @memberof ItemAmember
     */
    amember_product_id?: string;
}

export function ItemAmemberFromJSON(json: any): ItemAmember {
    return ItemAmemberFromJSONTyped(json, false);
}

export function ItemAmemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemAmember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amember_payment_duration_days': !exists(json, 'amember_payment_duration_days') ? undefined : json['amember_payment_duration_days'],
        'amember_product_id': !exists(json, 'amember_product_id') ? undefined : json['amember_product_id'],
    };
}

export function ItemAmemberToJSON(value?: ItemAmember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amember_payment_duration_days': value.amember_payment_duration_days,
        'amember_product_id': value.amember_product_id,
    };
}

