/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemEbayMarketListing
 */
export interface ItemEbayMarketListing {
    /**
     * Auction ID
     * @type {string}
     * @memberof ItemEbayMarketListing
     */
    auction_id?: string;
    /**
     * Price
     * @type {number}
     * @memberof ItemEbayMarketListing
     */
    price?: number;
    /**
     * Seller
     * @type {string}
     * @memberof ItemEbayMarketListing
     */
    seller?: string;
    /**
     * Shipping
     * @type {number}
     * @memberof ItemEbayMarketListing
     */
    shipping?: number;
    /**
     * Total
     * @type {number}
     * @memberof ItemEbayMarketListing
     */
    total?: number;
}



/**
 * Check if a given object implements the ItemEbayMarketListing interface.
 */
export function instanceOfItemEbayMarketListing(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemEbayMarketListingFromJSON(json: any): ItemEbayMarketListing {
    return ItemEbayMarketListingFromJSONTyped(json, false);
}

export function ItemEbayMarketListingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemEbayMarketListing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auction_id': !exists(json, 'auction_id') ? undefined : json['auction_id'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'seller': !exists(json, 'seller') ? undefined : json['seller'],
        'shipping': !exists(json, 'shipping') ? undefined : json['shipping'],
        'total': !exists(json, 'total') ? undefined : json['total'],
    };
}

export function ItemEbayMarketListingToJSON(value?: ItemEbayMarketListing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auction_id': value.auction_id,
        'price': value.price,
        'seller': value.seller,
        'shipping': value.shipping,
        'total': value.total,
    };
}

