/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemPricingTierLimit
 */
export interface ItemPricingTierLimit {
    /**
     * Cumulative order limit
     * @type {number}
     * @memberof ItemPricingTierLimit
     */
    cumulative_order_limit?: number;
    /**
     * Individual order limit
     * @type {number}
     * @memberof ItemPricingTierLimit
     */
    individual_order_limit?: number;
    /**
     * Multiple quantity
     * @type {number}
     * @memberof ItemPricingTierLimit
     */
    multiple_quantity?: number;
}

export function ItemPricingTierLimitFromJSON(json: any): ItemPricingTierLimit {
    return ItemPricingTierLimitFromJSONTyped(json, false);
}

export function ItemPricingTierLimitFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemPricingTierLimit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cumulative_order_limit': !exists(json, 'cumulative_order_limit') ? undefined : json['cumulative_order_limit'],
        'individual_order_limit': !exists(json, 'individual_order_limit') ? undefined : json['individual_order_limit'],
        'multiple_quantity': !exists(json, 'multiple_quantity') ? undefined : json['multiple_quantity'],
    };
}

export function ItemPricingTierLimitToJSON(value?: ItemPricingTierLimit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cumulative_order_limit': value.cumulative_order_limit,
        'individual_order_limit': value.individual_order_limit,
        'multiple_quantity': value.multiple_quantity,
    };
}

