/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemVariationOption
 */
export interface ItemVariationOption {
    /**
     * True if default option
     * @type {boolean}
     * @memberof ItemVariationOption
     */
    default_option?: boolean;
    /**
     * Multimedia object identifier
     * @type {number}
     * @memberof ItemVariationOption
     */
    merchant_item_multimedia_oid?: number;
    /**
     * Translated text instance id
     * @type {number}
     * @memberof ItemVariationOption
     */
    translated_text_instance_oid?: number;
    /**
     * Value
     * @type {string}
     * @memberof ItemVariationOption
     */
    value?: string;
}

// Define the constant array of keys
const MY_INTERFACE_KEYS: (keyof ItemVariationOption)[] = ["default_option", "merchant_item_multimedia_oid", "translated_text_instance_oid", "value"];

// Exported function to check for excess properties
export function hasExcessProperties(obj: any): boolean {
  const objKeys = Object.keys(obj);
  return objKeys.some(key => !MY_INTERFACE_KEYS.includes(key as keyof MyInterface));
}



/**
 * Check if a given object implements the ItemVariationOption interface.
 */
export function instanceOfItemVariationOption(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemVariationOptionFromJSON(json: any): ItemVariationOption {
    return ItemVariationOptionFromJSONTyped(json, false);
}

export function ItemVariationOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemVariationOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'default_option': !exists(json, 'default_option') ? undefined : json['default_option'],
        'merchant_item_multimedia_oid': !exists(json, 'merchant_item_multimedia_oid') ? undefined : json['merchant_item_multimedia_oid'],
        'translated_text_instance_oid': !exists(json, 'translated_text_instance_oid') ? undefined : json['translated_text_instance_oid'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ItemVariationOptionToJSON(value?: ItemVariationOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'default_option': value.default_option,
        'merchant_item_multimedia_oid': value.merchant_item_multimedia_oid,
        'translated_text_instance_oid': value.translated_text_instance_oid,
        'value': value.value,
    };
}

