/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderPaymentPayPal
 */
export interface OrderPaymentPayPal {
    /**
     * PayPal Customer ID
     * @type {string}
     * @memberof OrderPaymentPayPal
     */
    customer_id?: string;
    /**
     * PayPal Vault ID
     * @type {string}
     * @memberof OrderPaymentPayPal
     */
    vault_id?: string;
}

// Define the constant array of keys
const MY_INTERFACE_KEYS: (keyof OrderPaymentPayPal)[] = ["customer_id", "vault_id"];

// Exported function to check for excess properties
export function hasExcessProperties(obj: any): boolean {
  const objKeys = Object.keys(obj);
  return objKeys.some(key => !MY_INTERFACE_KEYS.includes(key as keyof MyInterface));
}



/**
 * Check if a given object implements the OrderPaymentPayPal interface.
 */
export function instanceOfOrderPaymentPayPal(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderPaymentPayPalFromJSON(json: any): OrderPaymentPayPal {
    return OrderPaymentPayPalFromJSONTyped(json, false);
}

export function OrderPaymentPayPalFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderPaymentPayPal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer_id': !exists(json, 'customer_id') ? undefined : json['customer_id'],
        'vault_id': !exists(json, 'vault_id') ? undefined : json['vault_id'],
    };
}

export function OrderPaymentPayPalToJSON(value?: OrderPaymentPayPal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer_id': value.customer_id,
        'vault_id': value.vault_id,
    };
}

