/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderPageViewParam
 */
export interface OrderPageViewParam {
    /**
     * Query string parameter name
     * @type {string}
     * @memberof OrderPageViewParam
     */
    name?: string;
    /**
     * Query string parameter value
     * @type {string}
     * @memberof OrderPageViewParam
     */
    value?: string;
}



/**
 * Check if a given object implements the OrderPageViewParam interface.
 */
export function instanceOfOrderPageViewParam(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderPageViewParamFromJSON(json: any): OrderPageViewParam {
    return OrderPageViewParamFromJSONTyped(json, false);
}

export function OrderPageViewParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderPageViewParam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function OrderPageViewParamToJSON(value?: OrderPageViewParam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}

