/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderQueryBatch
 */
export interface OrderQueryBatch {
    /**
     * Order IDs
     * @type {Array<string>}
     * @memberof OrderQueryBatch
     */
    order_ids?: Array<string>;
}

export function OrderQueryBatchFromJSON(json: any): OrderQueryBatch {
    return OrderQueryBatchFromJSONTyped(json, false);
}

export function OrderQueryBatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderQueryBatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order_ids': !exists(json, 'order_ids') ? undefined : json['order_ids'],
    };
}

export function OrderQueryBatchToJSON(value?: OrderQueryBatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order_ids': value.order_ids,
    };
}

