/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface OrderInvoiceResponse
 */
export interface OrderInvoiceResponse {
    /**
     * 
     * @type {ModelError}
     * @memberof OrderInvoiceResponse
     */
    error?: ModelError;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof OrderInvoiceResponse
     */
    metadata?: ResponseMetadata;
    /**
     * pdf_base64
     * @type {string}
     * @memberof OrderInvoiceResponse
     */
    pdfBase64?: string;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof OrderInvoiceResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Warning}
     * @memberof OrderInvoiceResponse
     */
    warning?: Warning;
}

export function OrderInvoiceResponseFromJSON(json: any): OrderInvoiceResponse {
    return OrderInvoiceResponseFromJSONTyped(json, false);
}

export function OrderInvoiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderInvoiceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'pdfBase64': !exists(json, 'pdfBase64') ? undefined : json['pdfBase64'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function OrderInvoiceResponseToJSON(value?: OrderInvoiceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ModelErrorToJSON(value.error),
        'metadata': ResponseMetadataToJSON(value.metadata),
        'pdfBase64': value.pdfBase64,
        'success': value.success,
        'warning': WarningToJSON(value.warning),
    };
}

