/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportDataSetQueryOrderByColumn
 */
export interface ReportDataSetQueryOrderByColumn {
    /**
     * 
     * @type {boolean}
     * @memberof ReportDataSetQueryOrderByColumn
     */
    ascending?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReportDataSetQueryOrderByColumn
     */
    column_name?: string;
}

// Define the constant array of keys
const MY_INTERFACE_KEYS: (keyof ReportDataSetQueryOrderByColumn)[] = ["ascending", "column_name"];

// Exported function to check for excess properties
export function hasExcessProperties(obj: any): boolean {
  const objKeys = Object.keys(obj);
  return objKeys.some(key => !MY_INTERFACE_KEYS.includes(key as keyof MyInterface));
}



/**
 * Check if a given object implements the ReportDataSetQueryOrderByColumn interface.
 */
export function instanceOfReportDataSetQueryOrderByColumn(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReportDataSetQueryOrderByColumnFromJSON(json: any): ReportDataSetQueryOrderByColumn {
    return ReportDataSetQueryOrderByColumnFromJSONTyped(json, false);
}

export function ReportDataSetQueryOrderByColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportDataSetQueryOrderByColumn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ascending': !exists(json, 'ascending') ? undefined : json['ascending'],
        'column_name': !exists(json, 'column_name') ? undefined : json['column_name'],
    };
}

export function ReportDataSetQueryOrderByColumnToJSON(value?: ReportDataSetQueryOrderByColumn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ascending': value.ascending,
        'column_name': value.column_name,
    };
}

