/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ScreenRecordingFilterPageViewEvent,
    ScreenRecordingFilterPageViewEventFromJSON,
    ScreenRecordingFilterPageViewEventFromJSONTyped,
    ScreenRecordingFilterPageViewEventToJSON,
} from './ScreenRecordingFilterPageViewEvent';
import {
    ScreenRecordingFilterPageViewParam,
    ScreenRecordingFilterPageViewParamFromJSON,
    ScreenRecordingFilterPageViewParamFromJSONTyped,
    ScreenRecordingFilterPageViewParamToJSON,
} from './ScreenRecordingFilterPageViewParam';
import {
    ScreenRecordingFilterPageViewReferrerParam,
    ScreenRecordingFilterPageViewReferrerParamFromJSON,
    ScreenRecordingFilterPageViewReferrerParamFromJSONTyped,
    ScreenRecordingFilterPageViewReferrerParamToJSON,
} from './ScreenRecordingFilterPageViewReferrerParam';
import {
    ScreenRecordingFilterRangeInteger,
    ScreenRecordingFilterRangeIntegerFromJSON,
    ScreenRecordingFilterRangeIntegerFromJSONTyped,
    ScreenRecordingFilterRangeIntegerToJSON,
} from './ScreenRecordingFilterRangeInteger';
import {
    ScreenRecordingFilterStringSearch,
    ScreenRecordingFilterStringSearchFromJSON,
    ScreenRecordingFilterStringSearchFromJSONTyped,
    ScreenRecordingFilterStringSearchToJSON,
} from './ScreenRecordingFilterStringSearch';

/**
 * 
 * @export
 * @interface ScreenRecordingFilterPageView
 */
export interface ScreenRecordingFilterPageView {
    /**
     * 
     * @type {ScreenRecordingFilterStringSearch}
     * @memberof ScreenRecordingFilterPageView
     */
    domain?: ScreenRecordingFilterStringSearch;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenRecordingFilterPageView
     */
    domain_filter?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenRecordingFilterPageView
     */
    event_name_filter?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenRecordingFilterPageView
     */
    event_param_name_filter?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenRecordingFilterPageView
     */
    event_param_value_filter?: boolean;
    /**
     * 
     * @type {Array<ScreenRecordingFilterPageViewEvent>}
     * @memberof ScreenRecordingFilterPageView
     */
    events?: Array<ScreenRecordingFilterPageViewEvent>;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenRecordingFilterPageView
     */
    param_name_filter?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenRecordingFilterPageView
     */
    param_value_filter?: boolean;
    /**
     * 
     * @type {Array<ScreenRecordingFilterPageViewParam>}
     * @memberof ScreenRecordingFilterPageView
     */
    params?: Array<ScreenRecordingFilterPageViewParam>;
    /**
     * 
     * @type {ScreenRecordingFilterStringSearch}
     * @memberof ScreenRecordingFilterPageView
     */
    referrer?: ScreenRecordingFilterStringSearch;
    /**
     * 
     * @type {Array<ScreenRecordingFilterPageViewReferrerParam>}
     * @memberof ScreenRecordingFilterPageView
     */
    referrer_params?: Array<ScreenRecordingFilterPageViewReferrerParam>;
    /**
     * 
     * @type {ScreenRecordingFilterStringSearch}
     * @memberof ScreenRecordingFilterPageView
     */
    referrer_raw?: ScreenRecordingFilterStringSearch;
    /**
     * 
     * @type {ScreenRecordingFilterRangeInteger}
     * @memberof ScreenRecordingFilterPageView
     */
    time_on_page?: ScreenRecordingFilterRangeInteger;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenRecordingFilterPageView
     */
    time_on_page_max_filter?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenRecordingFilterPageView
     */
    time_on_page_min_filter?: boolean;
    /**
     * 
     * @type {ScreenRecordingFilterStringSearch}
     * @memberof ScreenRecordingFilterPageView
     */
    url?: ScreenRecordingFilterStringSearch;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenRecordingFilterPageView
     */
    url_filter?: boolean;
}

export function ScreenRecordingFilterPageViewFromJSON(json: any): ScreenRecordingFilterPageView {
    return ScreenRecordingFilterPageViewFromJSONTyped(json, false);
}

export function ScreenRecordingFilterPageViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenRecordingFilterPageView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'domain': !exists(json, 'domain') ? undefined : ScreenRecordingFilterStringSearchFromJSON(json['domain']),
        'domain_filter': !exists(json, 'domain_filter') ? undefined : json['domain_filter'],
        'event_name_filter': !exists(json, 'event_name_filter') ? undefined : json['event_name_filter'],
        'event_param_name_filter': !exists(json, 'event_param_name_filter') ? undefined : json['event_param_name_filter'],
        'event_param_value_filter': !exists(json, 'event_param_value_filter') ? undefined : json['event_param_value_filter'],
        'events': !exists(json, 'events') ? undefined : ((json['events'] as Array<any>).map(ScreenRecordingFilterPageViewEventFromJSON)),
        'param_name_filter': !exists(json, 'param_name_filter') ? undefined : json['param_name_filter'],
        'param_value_filter': !exists(json, 'param_value_filter') ? undefined : json['param_value_filter'],
        'params': !exists(json, 'params') ? undefined : ((json['params'] as Array<any>).map(ScreenRecordingFilterPageViewParamFromJSON)),
        'referrer': !exists(json, 'referrer') ? undefined : ScreenRecordingFilterStringSearchFromJSON(json['referrer']),
        'referrer_params': !exists(json, 'referrer_params') ? undefined : ((json['referrer_params'] as Array<any>).map(ScreenRecordingFilterPageViewReferrerParamFromJSON)),
        'referrer_raw': !exists(json, 'referrer_raw') ? undefined : ScreenRecordingFilterStringSearchFromJSON(json['referrer_raw']),
        'time_on_page': !exists(json, 'time_on_page') ? undefined : ScreenRecordingFilterRangeIntegerFromJSON(json['time_on_page']),
        'time_on_page_max_filter': !exists(json, 'time_on_page_max_filter') ? undefined : json['time_on_page_max_filter'],
        'time_on_page_min_filter': !exists(json, 'time_on_page_min_filter') ? undefined : json['time_on_page_min_filter'],
        'url': !exists(json, 'url') ? undefined : ScreenRecordingFilterStringSearchFromJSON(json['url']),
        'url_filter': !exists(json, 'url_filter') ? undefined : json['url_filter'],
    };
}

export function ScreenRecordingFilterPageViewToJSON(value?: ScreenRecordingFilterPageView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'domain': ScreenRecordingFilterStringSearchToJSON(value.domain),
        'domain_filter': value.domain_filter,
        'event_name_filter': value.event_name_filter,
        'event_param_name_filter': value.event_param_name_filter,
        'event_param_value_filter': value.event_param_value_filter,
        'events': value.events === undefined ? undefined : ((value.events as Array<any>).map(ScreenRecordingFilterPageViewEventToJSON)),
        'param_name_filter': value.param_name_filter,
        'param_value_filter': value.param_value_filter,
        'params': value.params === undefined ? undefined : ((value.params as Array<any>).map(ScreenRecordingFilterPageViewParamToJSON)),
        'referrer': ScreenRecordingFilterStringSearchToJSON(value.referrer),
        'referrer_params': value.referrer_params === undefined ? undefined : ((value.referrer_params as Array<any>).map(ScreenRecordingFilterPageViewReferrerParamToJSON)),
        'referrer_raw': ScreenRecordingFilterStringSearchToJSON(value.referrer_raw),
        'time_on_page': ScreenRecordingFilterRangeIntegerToJSON(value.time_on_page),
        'time_on_page_max_filter': value.time_on_page_max_filter,
        'time_on_page_min_filter': value.time_on_page_min_filter,
        'url': ScreenRecordingFilterStringSearchToJSON(value.url),
        'url_filter': value.url_filter,
    };
}

