/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbThemeJobResponse
 */
export interface SfvbThemeJobResponse {
    /**
     * True once the job has stopped, whether it succeeded or failed.
     * @type {boolean}
     * @memberof SfvbThemeJobResponse
     */
    complete?: boolean;
    /**
     * Human readable description of the job.
     * @type {string}
     * @memberof SfvbThemeJobResponse
     */
    description?: string;
    /**
     * Failure detail.  Populated only when status is error.
     * @type {string}
     * @memberof SfvbThemeJobResponse
     */
    error_message?: string;
    /**
     * When the job stopped.  Null until it does.
     * @type {string}
     * @memberof SfvbThemeJobResponse
     */
    finished_dts?: string;
    /**
     * Job handle.  Poll getSfvbThemeJob with this.
     * @type {number}
     * @memberof SfvbThemeJobResponse
     */
    job_id?: number;
    /**
     * Percent complete, 0-100.
     * @type {number}
     * @memberof SfvbThemeJobResponse
     */
    progress?: number;
    /**
     * What the job is doing right now, for example 'Duplicating locale text'.
     * @type {string}
     * @memberof SfvbThemeJobResponse
     */
    progress_description?: string;
    /**
     * When the job started running.  Null until it does.
     * @type {string}
     * @memberof SfvbThemeJobResponse
     */
    started_dts?: string;
    /**
     * Raw job status.
     * @type {string}
     * @memberof SfvbThemeJobResponse
     */
    status?: SfvbThemeJobResponseStatusEnum;
    /**
     * When the job was queued.
     * @type {string}
     * @memberof SfvbThemeJobResponse
     */
    submitted_dts?: string;
    /**
     * True only when the job finished successfully.  Check complete first.
     * @type {boolean}
     * @memberof SfvbThemeJobResponse
     */
    success?: boolean;
    /**
     * Path the new theme was created at.  Returned when the job is started; the theme oid itself is NOT returned, because the job's product is a plain text report rather than a structured result.  Once the job completes, list themes and match on this path.
     * @type {string}
     * @memberof SfvbThemeJobResponse
     */
    target_path?: string;
}



/**
 * @export
 */
export const SfvbThemeJobResponseStatusEnum = {
    Submitted: 'submitted',
    Running: 'running',
    RunningLocal: 'running local',
    Finished: 'finished',
    Error: 'error'
} as const;
export type SfvbThemeJobResponseStatusEnum = typeof SfvbThemeJobResponseStatusEnum[keyof typeof SfvbThemeJobResponseStatusEnum];


/**
 * Check if a given object implements the SfvbThemeJobResponse interface.
 */
export function instanceOfSfvbThemeJobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbThemeJobResponseFromJSON(json: any): SfvbThemeJobResponse {
    return SfvbThemeJobResponseFromJSONTyped(json, false);
}

export function SfvbThemeJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbThemeJobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'complete': !exists(json, 'complete') ? undefined : json['complete'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'error_message': !exists(json, 'error_message') ? undefined : json['error_message'],
        'finished_dts': !exists(json, 'finished_dts') ? undefined : json['finished_dts'],
        'job_id': !exists(json, 'job_id') ? undefined : json['job_id'],
        'progress': !exists(json, 'progress') ? undefined : json['progress'],
        'progress_description': !exists(json, 'progress_description') ? undefined : json['progress_description'],
        'started_dts': !exists(json, 'started_dts') ? undefined : json['started_dts'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'submitted_dts': !exists(json, 'submitted_dts') ? undefined : json['submitted_dts'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'target_path': !exists(json, 'target_path') ? undefined : json['target_path'],
    };
}

export function SfvbThemeJobResponseToJSON(value?: SfvbThemeJobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'complete': value.complete,
        'description': value.description,
        'error_message': value.error_message,
        'finished_dts': value.finished_dts,
        'job_id': value.job_id,
        'progress': value.progress,
        'progress_description': value.progress_description,
        'started_dts': value.started_dts,
        'status': value.status,
        'submitted_dts': value.submitted_dts,
        'success': value.success,
        'target_path': value.target_path,
    };
}

