/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SfvbRecordingEvent,
    SfvbRecordingEventFromJSON,
    SfvbRecordingEventFromJSONTyped,
    SfvbRecordingEventToJSON,
} from './SfvbRecordingEvent';
import {
    SfvbRecordingParameter,
    SfvbRecordingParameterFromJSON,
    SfvbRecordingParameterFromJSONTyped,
    SfvbRecordingParameterToJSON,
} from './SfvbRecordingParameter';

/**
 * 
 * @export
 * @interface SfvbRecordingPageView
 */
export interface SfvbRecordingPageView {
    /**
     * The host name of the address.
     * @type {string}
     * @memberof SfvbRecordingPageView
     */
    domain?: string;
    /**
     * Named events on this page view in time order, such as rage clicks and script errors.
     * @type {Array<SfvbRecordingEvent>}
     * @memberof SfvbRecordingPageView
     */
    events?: Array<SfvbRecordingEvent>;
    /**
     * When recording of this page view began, ISO-8601 in UTC.
     * @type {string}
     * @memberof SfvbRecordingPageView
     */
    first_event_timestamp?: string;
    /**
     * When recording of this page view ended, ISO-8601 in UTC.
     * @type {string}
     * @memberof SfvbRecordingPageView
     */
    last_event_timestamp?: string;
    /**
     * True when no replay events were stored for this page view.
     * @type {boolean}
     * @memberof SfvbRecordingPageView
     */
    missing_events?: boolean;
    /**
     * The query string parameters on the address.
     * @type {Array<SfvbRecordingParameter>}
     * @memberof SfvbRecordingPageView
     */
    params?: Array<SfvbRecordingParameter>;
    /**
     * The referring address, when there was one.
     * @type {string}
     * @memberof SfvbRecordingPageView
     */
    referrer?: string;
    /**
     * Identifies this page view when fetching its replay events.
     * @type {string}
     * @memberof SfvbRecordingPageView
     */
    screen_recording_page_view_uuid?: string;
    /**
     * Seconds the visitor spent on the page.
     * @type {number}
     * @memberof SfvbRecordingPageView
     */
    time_on_page?: number;
    /**
     * Milliseconds until DOMContentLoaded fired.
     * @type {number}
     * @memberof SfvbRecordingPageView
     */
    timing_dom_content_loaded?: number;
    /**
     * Milliseconds until the load event fired.
     * @type {number}
     * @memberof SfvbRecordingPageView
     */
    timing_loaded?: number;
    /**
     * True when the recorder stopped storing events part way through this page view.
     * @type {boolean}
     * @memberof SfvbRecordingPageView
     */
    truncated_events?: boolean;
    /**
     * The address the visitor viewed.
     * @type {string}
     * @memberof SfvbRecordingPageView
     */
    url?: string;
}



/**
 * Check if a given object implements the SfvbRecordingPageView interface.
 */
export function instanceOfSfvbRecordingPageView(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbRecordingPageViewFromJSON(json: any): SfvbRecordingPageView {
    return SfvbRecordingPageViewFromJSONTyped(json, false);
}

export function SfvbRecordingPageViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbRecordingPageView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'domain': !exists(json, 'domain') ? undefined : json['domain'],
        'events': !exists(json, 'events') ? undefined : ((json['events'] as Array<any>).map(SfvbRecordingEventFromJSON)),
        'first_event_timestamp': !exists(json, 'first_event_timestamp') ? undefined : json['first_event_timestamp'],
        'last_event_timestamp': !exists(json, 'last_event_timestamp') ? undefined : json['last_event_timestamp'],
        'missing_events': !exists(json, 'missing_events') ? undefined : json['missing_events'],
        'params': !exists(json, 'params') ? undefined : ((json['params'] as Array<any>).map(SfvbRecordingParameterFromJSON)),
        'referrer': !exists(json, 'referrer') ? undefined : json['referrer'],
        'screen_recording_page_view_uuid': !exists(json, 'screen_recording_page_view_uuid') ? undefined : json['screen_recording_page_view_uuid'],
        'time_on_page': !exists(json, 'time_on_page') ? undefined : json['time_on_page'],
        'timing_dom_content_loaded': !exists(json, 'timing_dom_content_loaded') ? undefined : json['timing_dom_content_loaded'],
        'timing_loaded': !exists(json, 'timing_loaded') ? undefined : json['timing_loaded'],
        'truncated_events': !exists(json, 'truncated_events') ? undefined : json['truncated_events'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function SfvbRecordingPageViewToJSON(value?: SfvbRecordingPageView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'domain': value.domain,
        'events': value.events === undefined ? undefined : ((value.events as Array<any>).map(SfvbRecordingEventToJSON)),
        'first_event_timestamp': value.first_event_timestamp,
        'last_event_timestamp': value.last_event_timestamp,
        'missing_events': value.missing_events,
        'params': value.params === undefined ? undefined : ((value.params as Array<any>).map(SfvbRecordingParameterToJSON)),
        'referrer': value.referrer,
        'screen_recording_page_view_uuid': value.screen_recording_page_view_uuid,
        'time_on_page': value.time_on_page,
        'timing_dom_content_loaded': value.timing_dom_content_loaded,
        'timing_loaded': value.timing_loaded,
        'truncated_events': value.truncated_events,
        'url': value.url,
    };
}

