/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbBlogPostImage
 */
export interface SfvbBlogPostImage {
    /**
     * The image's oid.  Detach names it this way.
     * @type {number}
     * @memberof SfvbBlogPostImage
     */
    blog_post_multimedia_oid?: number;
    /**
     * The image code, or null for the default image and for an image used only in the body.
     * @type {string}
     * @memberof SfvbBlogPostImage
     */
    code?: string;
    /**
     * True for the post's default image, which a blogpostimage element and og image use.
     * @type {boolean}
     * @memberof SfvbBlogPostImage
     */
    default_image?: boolean;
    /**
     * The description stored with the image, used as its alt text.
     * @type {string}
     * @memberof SfvbBlogPostImage
     */
    description?: string;
    /**
     * The image's file name.
     * @type {string}
     * @memberof SfvbBlogPostImage
     */
    filename?: string;
    /**
     * Height in pixels, when it could be measured.
     * @type {number}
     * @memberof SfvbBlogPostImage
     */
    height?: number;
    /**
     * The address to use in the post body, for example in an img src.  The storefront serves it from its image CDN once the image has been copied there.
     * @type {string}
     * @memberof SfvbBlogPostImage
     */
    url?: string;
    /**
     * Width in pixels, when it could be measured.
     * @type {number}
     * @memberof SfvbBlogPostImage
     */
    width?: number;
}



/**
 * Check if a given object implements the SfvbBlogPostImage interface.
 */
export function instanceOfSfvbBlogPostImage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbBlogPostImageFromJSON(json: any): SfvbBlogPostImage {
    return SfvbBlogPostImageFromJSONTyped(json, false);
}

export function SfvbBlogPostImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbBlogPostImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blog_post_multimedia_oid': !exists(json, 'blog_post_multimedia_oid') ? undefined : json['blog_post_multimedia_oid'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'default_image': !exists(json, 'default_image') ? undefined : json['default_image'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'width': !exists(json, 'width') ? undefined : json['width'],
    };
}

export function SfvbBlogPostImageToJSON(value?: SfvbBlogPostImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blog_post_multimedia_oid': value.blog_post_multimedia_oid,
        'code': value.code,
        'default_image': value.default_image,
        'description': value.description,
        'filename': value.filename,
        'height': value.height,
        'url': value.url,
        'width': value.width,
    };
}

