/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbItemAttributeUpdate
 */
export interface SfvbItemAttributeUpdate {
    /**
     * The attribute to change, matched without regard to case.  An attribute that does not exist yet is created.
     * @type {string}
     * @memberof SfvbItemAttributeUpdate
     */
    name?: string;
    /**
     * Only consulted for a name no template declares, to say how the value should be validated and what the attribute is recorded as.  Ignored otherwise, because a declared attribute's type comes from the template that declares it.
     * @type {string}
     * @memberof SfvbItemAttributeUpdate
     */
    type?: SfvbItemAttributeUpdateTypeEnum;
    /**
     * The new value.  Send an empty string to clear it.  For the list types this is the JSON document as text, not a nested object - see the type's own format, because a shape the renderer cannot parse renders exactly like an attribute that was never set.
     * @type {string}
     * @memberof SfvbItemAttributeUpdate
     */
    value?: string;
}



/**
 * @export
 */
export const SfvbItemAttributeUpdateTypeEnum = {
    String: 'string',
    Multiline: 'multiline',
    Html: 'html',
    Simplelist: 'simplelist',
    Definitionlist: 'definitionlist',
    Videolist: 'videolist',
    Itemset: 'itemset',
    Mailinglist: 'mailinglist',
    Boolean: 'boolean',
    Integer: 'integer',
    Color: 'color',
    Rgba: 'rgba'
} as const;
export type SfvbItemAttributeUpdateTypeEnum = typeof SfvbItemAttributeUpdateTypeEnum[keyof typeof SfvbItemAttributeUpdateTypeEnum];


/**
 * Check if a given object implements the SfvbItemAttributeUpdate interface.
 */
export function instanceOfSfvbItemAttributeUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbItemAttributeUpdateFromJSON(json: any): SfvbItemAttributeUpdate {
    return SfvbItemAttributeUpdateFromJSONTyped(json, false);
}

export function SfvbItemAttributeUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbItemAttributeUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function SfvbItemAttributeUpdateToJSON(value?: SfvbItemAttributeUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'value': value.value,
    };
}

