/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbApprovalParams
 */
export interface SfvbApprovalParams {
    /**
     * The blog post, for blog_post.delete.
     * @type {number}
     * @memberof SfvbApprovalParams
     */
    blog_post_oid?: number;
    /**
     * The file path, for file.delete.  Exactly as the delete call will send it.
     * @type {string}
     * @memberof SfvbApprovalParams
     */
    path?: string;
}



/**
 * Check if a given object implements the SfvbApprovalParams interface.
 */
export function instanceOfSfvbApprovalParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbApprovalParamsFromJSON(json: any): SfvbApprovalParams {
    return SfvbApprovalParamsFromJSONTyped(json, false);
}

export function SfvbApprovalParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbApprovalParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blog_post_oid': !exists(json, 'blog_post_oid') ? undefined : json['blog_post_oid'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function SfvbApprovalParamsToJSON(value?: SfvbApprovalParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blog_post_oid': value.blog_post_oid,
        'path': value.path,
    };
}

