/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SfvbUpsellPath,
    SfvbUpsellPathFromJSON,
    SfvbUpsellPathFromJSONTyped,
    SfvbUpsellPathToJSON,
} from './SfvbUpsellPath';

/**
 * 
 * @export
 * @interface SfvbUpsellPathsResponse
 */
export interface SfvbUpsellPathsResponse {
    /**
     * Page size that was applied.
     * @type {number}
     * @memberof SfvbUpsellPathsResponse
     */
    max_results?: number;
    /**
     * Offset of the next page.  Omitted on the last page.
     * @type {number}
     * @memberof SfvbUpsellPathsResponse
     */
    next_offset?: number;
    /**
     * Offset this page starts at.
     * @type {number}
     * @memberof SfvbUpsellPathsResponse
     */
    offset?: number;
    /**
     * Paths on this page.
     * @type {number}
     * @memberof SfvbUpsellPathsResponse
     */
    result_count?: number;
    /**
     * Paths matching the filters, across all pages.
     * @type {number}
     * @memberof SfvbUpsellPathsResponse
     */
    total_count?: number;
    /**
     * The paths on this page, first to last.
     * @type {Array<SfvbUpsellPath>}
     * @memberof SfvbUpsellPathsResponse
     */
    upsell_paths?: Array<SfvbUpsellPath>;
}



/**
 * Check if a given object implements the SfvbUpsellPathsResponse interface.
 */
export function instanceOfSfvbUpsellPathsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbUpsellPathsResponseFromJSON(json: any): SfvbUpsellPathsResponse {
    return SfvbUpsellPathsResponseFromJSONTyped(json, false);
}

export function SfvbUpsellPathsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbUpsellPathsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'max_results': !exists(json, 'max_results') ? undefined : json['max_results'],
        'next_offset': !exists(json, 'next_offset') ? undefined : json['next_offset'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'result_count': !exists(json, 'result_count') ? undefined : json['result_count'],
        'total_count': !exists(json, 'total_count') ? undefined : json['total_count'],
        'upsell_paths': !exists(json, 'upsell_paths') ? undefined : ((json['upsell_paths'] as Array<any>).map(SfvbUpsellPathFromJSON)),
    };
}

export function SfvbUpsellPathsResponseToJSON(value?: SfvbUpsellPathsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'max_results': value.max_results,
        'next_offset': value.next_offset,
        'offset': value.offset,
        'result_count': value.result_count,
        'total_count': value.total_count,
        'upsell_paths': value.upsell_paths === undefined ? undefined : ((value.upsell_paths as Array<any>).map(SfvbUpsellPathToJSON)),
    };
}

