/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SfvbUpsellItemLogicItem,
    SfvbUpsellItemLogicItemFromJSON,
    SfvbUpsellItemLogicItemFromJSONTyped,
    SfvbUpsellItemLogicItemToJSON,
} from './SfvbUpsellItemLogicItem';

/**
 * 
 * @export
 * @interface SfvbUpsellItemLogic
 */
export interface SfvbUpsellItemLogic {
    /**
     * The items this logic looks at.  Every item id must exist on the merchant account.
     * @type {Array<SfvbUpsellItemLogicItem>}
     * @memberof SfvbUpsellItemLogic
     */
    items?: Array<SfvbUpsellItemLogicItem>;
    /**
     * How items is read.  contains_any, contains_all, all, any or total.  Omitted or null means no item logic.
     * @type {string}
     * @memberof SfvbUpsellItemLogic
     */
    logic?: string;
    /**
     * For total only.  The quantity the summed quantity is compared with.
     * @type {number}
     * @memberof SfvbUpsellItemLogic
     */
    total_quantity_comparison?: number;
    /**
     * For total only.  The comparison applied to the summed quantity.  One of <, <=, =, >=, >.
     * @type {string}
     * @memberof SfvbUpsellItemLogic
     */
    total_quantity_operator?: string;
}



/**
 * Check if a given object implements the SfvbUpsellItemLogic interface.
 */
export function instanceOfSfvbUpsellItemLogic(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbUpsellItemLogicFromJSON(json: any): SfvbUpsellItemLogic {
    return SfvbUpsellItemLogicFromJSONTyped(json, false);
}

export function SfvbUpsellItemLogicFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbUpsellItemLogic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(SfvbUpsellItemLogicItemFromJSON)),
        'logic': !exists(json, 'logic') ? undefined : json['logic'],
        'total_quantity_comparison': !exists(json, 'total_quantity_comparison') ? undefined : json['total_quantity_comparison'],
        'total_quantity_operator': !exists(json, 'total_quantity_operator') ? undefined : json['total_quantity_operator'],
    };
}

export function SfvbUpsellItemLogicToJSON(value?: SfvbUpsellItemLogic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(SfvbUpsellItemLogicItemToJSON)),
        'logic': value.logic,
        'total_quantity_comparison': value.total_quantity_comparison,
        'total_quantity_operator': value.total_quantity_operator,
    };
}

