/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbI18nTranslation
 */
export interface SfvbI18nTranslation {
    /**
     * The three-letter language code.
     * @type {string}
     * @memberof SfvbI18nTranslation
     */
    language?: string;
    /**
     * hand for a translation someone wrote, machine for a machine translation, pending when one is queued, none when nothing exists yet (it is made the first time the text renders in that language).
     * @type {string}
     * @memberof SfvbI18nTranslation
     */
    source?: string;
    /**
     * The text a shopper sees in that language.  Absent when source is none or pending.
     * @type {string}
     * @memberof SfvbI18nTranslation
     */
    text?: string;
}



/**
 * Check if a given object implements the SfvbI18nTranslation interface.
 */
export function instanceOfSfvbI18nTranslation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbI18nTranslationFromJSON(json: any): SfvbI18nTranslation {
    return SfvbI18nTranslationFromJSONTyped(json, false);
}

export function SfvbI18nTranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbI18nTranslation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'language': !exists(json, 'language') ? undefined : json['language'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'text': !exists(json, 'text') ? undefined : json['text'],
    };
}

export function SfvbI18nTranslationToJSON(value?: SfvbI18nTranslation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'language': value.language,
        'source': value.source,
        'text': value.text,
    };
}

