/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbApprovalParams
 */
export interface SfvbApprovalParams {
    /**
     * The blog post, for blog_post.delete.
     * @type {number}
     * @memberof SfvbApprovalParams
     */
    blog_post_oid?: number;
    /**
     * For file.put_script, the SHA-256 of the exact bytes approved.  Set by the server, never by the caller.  The write must send bytes with this hash.
     * @type {string}
     * @memberof SfvbApprovalParams
     */
    content_sha256?: string;
    /**
     * The file path, for file.delete and file.put_script.  Exactly as the gated call will send it.
     * @type {string}
     * @memberof SfvbApprovalParams
     */
    path?: string;
    /**
     * For redirect.delete_batch, the plan_hash of the exact rows approved.  Set by the server.  The batch delete must send rows with this hash.
     * @type {string}
     * @memberof SfvbApprovalParams
     */
    rows_sha256?: string;
    /**
     * For redirect.delete_batch, how many rules the batch would delete when it was requested.  Set by the server.
     * @type {number}
     * @memberof SfvbApprovalParams
     */
    rule_count?: number;
    /**
     * For file.put_script, the history version a revert restores.  Leave it out, and send content instead, for a write.
     * @type {number}
     * @memberof SfvbApprovalParams
     */
    version?: number;
}



/**
 * Check if a given object implements the SfvbApprovalParams interface.
 */
export function instanceOfSfvbApprovalParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbApprovalParamsFromJSON(json: any): SfvbApprovalParams {
    return SfvbApprovalParamsFromJSONTyped(json, false);
}

export function SfvbApprovalParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbApprovalParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blog_post_oid': !exists(json, 'blog_post_oid') ? undefined : json['blog_post_oid'],
        'content_sha256': !exists(json, 'content_sha256') ? undefined : json['content_sha256'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'rows_sha256': !exists(json, 'rows_sha256') ? undefined : json['rows_sha256'],
        'rule_count': !exists(json, 'rule_count') ? undefined : json['rule_count'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function SfvbApprovalParamsToJSON(value?: SfvbApprovalParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blog_post_oid': value.blog_post_oid,
        'content_sha256': value.content_sha256,
        'path': value.path,
        'rows_sha256': value.rows_sha256,
        'rule_count': value.rule_count,
        'version': value.version,
    };
}

