/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SfvbItemAttributeBatchRow,
    SfvbItemAttributeBatchRowFromJSON,
    SfvbItemAttributeBatchRowFromJSONTyped,
    SfvbItemAttributeBatchRowToJSON,
} from './SfvbItemAttributeBatchRow';

/**
 * 
 * @export
 * @interface SfvbItemAttributeBatchRequest
 */
export interface SfvbItemAttributeBatchRequest {
    /**
     * From the dry run.  Required to apply, with exactly the rows the dry run answered as change.
     * @type {string}
     * @memberof SfvbItemAttributeBatchRequest
     */
    plan_hash?: string;
    /**
     * The changes, up to 5,000 rows on up to 500 items.  Each item and name at most once.
     * @type {Array<SfvbItemAttributeBatchRow>}
     * @memberof SfvbItemAttributeBatchRequest
     */
    rows?: Array<SfvbItemAttributeBatchRow>;
}



/**
 * Check if a given object implements the SfvbItemAttributeBatchRequest interface.
 */
export function instanceOfSfvbItemAttributeBatchRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbItemAttributeBatchRequestFromJSON(json: any): SfvbItemAttributeBatchRequest {
    return SfvbItemAttributeBatchRequestFromJSONTyped(json, false);
}

export function SfvbItemAttributeBatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbItemAttributeBatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plan_hash': !exists(json, 'plan_hash') ? undefined : json['plan_hash'],
        'rows': !exists(json, 'rows') ? undefined : ((json['rows'] as Array<any>).map(SfvbItemAttributeBatchRowFromJSON)),
    };
}

export function SfvbItemAttributeBatchRequestToJSON(value?: SfvbItemAttributeBatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plan_hash': value.plan_hash,
        'rows': value.rows === undefined ? undefined : ((value.rows as Array<any>).map(SfvbItemAttributeBatchRowToJSON)),
    };
}

