/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbValidateRequest
 */
export interface SfvbValidateRequest {
    /**
     * The container JSON to validate.
     * @type {string}
     * @memberof SfvbValidateRequest
     */
    cjson?: string;
    /**
     * Container name it will be stored under, for example upsell-offer or email-footer.  Some rules key off the name.
     * @type {string}
     * @memberof SfvbValidateRequest
     */
    containerName?: string;
    /**
     * Include quality warnings as well as errors.  Defaults to true.
     * @type {boolean}
     * @memberof SfvbValidateRequest
     */
    includeWarnings?: boolean;
    /**
     * For email containers, whether this is a marketing email.  Marketing emails carry CAN-SPAM footer requirements that transactional emails do not.
     * @type {boolean}
     * @memberof SfvbValidateRequest
     */
    marketingEmail?: boolean;
    /**
     * Where this container is destined to live.  Determines which contextual rules apply.
     * @type {string}
     * @memberof SfvbValidateRequest
     */
    ownerType?: SfvbValidateRequestOwnerTypeEnum;
}



/**
 * @export
 */
export const SfvbValidateRequestOwnerTypeEnum = {
    Theme: 'theme',
    Page: 'page',
    Item: 'item',
    Upsell: 'upsell',
    Email: 'email',
    Postcard: 'postcard'
} as const;
export type SfvbValidateRequestOwnerTypeEnum = typeof SfvbValidateRequestOwnerTypeEnum[keyof typeof SfvbValidateRequestOwnerTypeEnum];


/**
 * Check if a given object implements the SfvbValidateRequest interface.
 */
export function instanceOfSfvbValidateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbValidateRequestFromJSON(json: any): SfvbValidateRequest {
    return SfvbValidateRequestFromJSONTyped(json, false);
}

export function SfvbValidateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbValidateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cjson': !exists(json, 'cjson') ? undefined : json['cjson'],
        'containerName': !exists(json, 'containerName') ? undefined : json['containerName'],
        'includeWarnings': !exists(json, 'includeWarnings') ? undefined : json['includeWarnings'],
        'marketingEmail': !exists(json, 'marketingEmail') ? undefined : json['marketingEmail'],
        'ownerType': !exists(json, 'ownerType') ? undefined : json['ownerType'],
    };
}

export function SfvbValidateRequestToJSON(value?: SfvbValidateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cjson': value.cjson,
        'containerName': value.containerName,
        'includeWarnings': value.includeWarnings,
        'marketingEmail': value.marketingEmail,
        'ownerType': value.ownerType,
    };
}

