/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbLibraryTaxonomyCatalog
 */
export interface SfvbLibraryTaxonomyCatalog {
    /**
     * purpose, section, industry and style, each with its allowed tags.
     * @type {object}
     * @memberof SfvbLibraryTaxonomyCatalog
     */
    dimensions?: object;
}



/**
 * Check if a given object implements the SfvbLibraryTaxonomyCatalog interface.
 */
export function instanceOfSfvbLibraryTaxonomyCatalog(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbLibraryTaxonomyCatalogFromJSON(json: any): SfvbLibraryTaxonomyCatalog {
    return SfvbLibraryTaxonomyCatalogFromJSONTyped(json, false);
}

export function SfvbLibraryTaxonomyCatalogFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbLibraryTaxonomyCatalog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dimensions': !exists(json, 'dimensions') ? undefined : json['dimensions'],
    };
}

export function SfvbLibraryTaxonomyCatalogToJSON(value?: SfvbLibraryTaxonomyCatalog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dimensions': value.dimensions,
    };
}

