/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbItemMultimediaRequest
 */
export interface SfvbItemMultimediaRequest {
    /**
     * Attach under this image code, the value an itemimage element's itemImageCode names.
     * @type {string}
     * @memberof SfvbItemMultimediaRequest
     */
    code?: string;
    /**
     * Attach as the item's default image, which is what an itemimage element with no code renders.  Name exactly one of this or code.
     * @type {boolean}
     * @memberof SfvbItemMultimediaRequest
     */
    _default?: boolean;
    /**
     * Stored with the image and rendered as its alt text.  Left out, the slot keeps the description it already had.
     * @type {string}
     * @memberof SfvbItemMultimediaRequest
     */
    description?: string;
    /**
     * Storefront file system path of the image to attach, such as /assets/img/mug-front.jpg.  Upload it with files/upload first.  Unlike a page image this does not have to sit in any particular folder, because an item has no folder of its own - the bytes are copied into the item's own storage on attach.
     * @type {string}
     * @memberof SfvbItemMultimediaRequest
     */
    path?: string;
}



/**
 * Check if a given object implements the SfvbItemMultimediaRequest interface.
 */
export function instanceOfSfvbItemMultimediaRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbItemMultimediaRequestFromJSON(json: any): SfvbItemMultimediaRequest {
    return SfvbItemMultimediaRequestFromJSONTyped(json, false);
}

export function SfvbItemMultimediaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbItemMultimediaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function SfvbItemMultimediaRequestToJSON(value?: SfvbItemMultimediaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'default': value._default,
        'description': value.description,
        'path': value.path,
    };
}

