/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbSiteAttributeUpdate
 */
export interface SfvbSiteAttributeUpdate {
    /**
     * Attribute name.  Matched without regard to case against what the storefront already has, so you do not have to reproduce the exact casing.  A name nothing matches creates a new attribute.
     * @type {string}
     * @memberof SfvbSiteAttributeUpdate
     */
    name?: string;
    /**
     * Only consulted when creating an attribute no template declares.  For a declared attribute the template's type always wins, because the templates decide it and not the caller.
     * @type {string}
     * @memberof SfvbSiteAttributeUpdate
     */
    type?: SfvbSiteAttributeUpdateTypeEnum;
    /**
     * The value to store.  An empty string clears it.  For html the markup is stored as given and rendered as given.  For boolean send the text true or false.
     * @type {string}
     * @memberof SfvbSiteAttributeUpdate
     */
    value?: string;
}



/**
 * @export
 */
export const SfvbSiteAttributeUpdateTypeEnum = {
    String: 'string',
    Multiline: 'multiline',
    Html: 'html',
    Boolean: 'boolean',
    Integer: 'integer',
    Color: 'color',
    Rgba: 'rgba'
} as const;
export type SfvbSiteAttributeUpdateTypeEnum = typeof SfvbSiteAttributeUpdateTypeEnum[keyof typeof SfvbSiteAttributeUpdateTypeEnum];


/**
 * Check if a given object implements the SfvbSiteAttributeUpdate interface.
 */
export function instanceOfSfvbSiteAttributeUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbSiteAttributeUpdateFromJSON(json: any): SfvbSiteAttributeUpdate {
    return SfvbSiteAttributeUpdateFromJSONTyped(json, false);
}

export function SfvbSiteAttributeUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbSiteAttributeUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function SfvbSiteAttributeUpdateToJSON(value?: SfvbSiteAttributeUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'value': value.value,
    };
}

