/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SfvbPageBlogPostSelector,
    SfvbPageBlogPostSelectorFromJSON,
    SfvbPageBlogPostSelectorFromJSONTyped,
    SfvbPageBlogPostSelectorToJSON,
} from './SfvbPageBlogPostSelector';
import {
    SfvbPageItemSelector,
    SfvbPageItemSelectorFromJSON,
    SfvbPageItemSelectorFromJSONTyped,
    SfvbPageItemSelectorToJSON,
} from './SfvbPageItemSelector';

/**
 * 
 * @export
 * @interface SfvbPageSelectors
 */
export interface SfvbPageSelectors {
    /**
     * The conditions that choose the page's blog posts.
     * @type {Array<SfvbPageBlogPostSelector>}
     * @memberof SfvbPageSelectors
     */
    blog_post_selectors?: Array<SfvbPageBlogPostSelector>;
    /**
     * The conditions that choose the page's items.  While there are any, the page's items are recalculated from them and cannot be assigned by hand.
     * @type {Array<SfvbPageItemSelector>}
     * @memberof SfvbPageSelectors
     */
    item_selectors?: Array<SfvbPageItemSelector>;
    /**
     * True when a blog post must meet every blog post selector, false when any one is enough.
     * @type {boolean}
     * @memberof SfvbPageSelectors
     */
    match_all_blog_post_selectors?: boolean;
    /**
     * True when an item must meet every item selector, false when meeting any one is enough.
     * @type {boolean}
     * @memberof SfvbPageSelectors
     */
    match_all_item_selectors?: boolean;
    /**
     * The page path.  Read only.
     * @type {string}
     * @memberof SfvbPageSelectors
     */
    path?: string;
}



/**
 * Check if a given object implements the SfvbPageSelectors interface.
 */
export function instanceOfSfvbPageSelectors(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbPageSelectorsFromJSON(json: any): SfvbPageSelectors {
    return SfvbPageSelectorsFromJSONTyped(json, false);
}

export function SfvbPageSelectorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbPageSelectors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blog_post_selectors': !exists(json, 'blog_post_selectors') ? undefined : ((json['blog_post_selectors'] as Array<any>).map(SfvbPageBlogPostSelectorFromJSON)),
        'item_selectors': !exists(json, 'item_selectors') ? undefined : ((json['item_selectors'] as Array<any>).map(SfvbPageItemSelectorFromJSON)),
        'match_all_blog_post_selectors': !exists(json, 'match_all_blog_post_selectors') ? undefined : json['match_all_blog_post_selectors'],
        'match_all_item_selectors': !exists(json, 'match_all_item_selectors') ? undefined : json['match_all_item_selectors'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function SfvbPageSelectorsToJSON(value?: SfvbPageSelectors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blog_post_selectors': value.blog_post_selectors === undefined ? undefined : ((value.blog_post_selectors as Array<any>).map(SfvbPageBlogPostSelectorToJSON)),
        'item_selectors': value.item_selectors === undefined ? undefined : ((value.item_selectors as Array<any>).map(SfvbPageItemSelectorToJSON)),
        'match_all_blog_post_selectors': value.match_all_blog_post_selectors,
        'match_all_item_selectors': value.match_all_item_selectors,
        'path': value.path,
    };
}

