/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SfvbItemRelatedItem,
    SfvbItemRelatedItemFromJSON,
    SfvbItemRelatedItemFromJSONTyped,
    SfvbItemRelatedItemToJSON,
} from './SfvbItemRelatedItem';

/**
 * 
 * @export
 * @interface SfvbItemRelatedRequest
 */
export interface SfvbItemRelatedRequest {
    /**
     * Left out keeps the stored value.
     * @type {boolean}
     * @memberof SfvbItemRelatedRequest
     */
    no_system_calculated_related_items?: boolean;
    /**
     * Left out keeps the stored value.
     * @type {boolean}
     * @memberof SfvbItemRelatedRequest
     */
    not_relatable?: boolean;
    /**
     * The merchant's related items, in order, up to 50.  An empty list removes them all.  The calculated (system) ones are kept.
     * @type {Array<SfvbItemRelatedItem>}
     * @memberof SfvbItemRelatedRequest
     */
    related_items?: Array<SfvbItemRelatedItem>;
}



/**
 * Check if a given object implements the SfvbItemRelatedRequest interface.
 */
export function instanceOfSfvbItemRelatedRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbItemRelatedRequestFromJSON(json: any): SfvbItemRelatedRequest {
    return SfvbItemRelatedRequestFromJSONTyped(json, false);
}

export function SfvbItemRelatedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbItemRelatedRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'no_system_calculated_related_items': !exists(json, 'no_system_calculated_related_items') ? undefined : json['no_system_calculated_related_items'],
        'not_relatable': !exists(json, 'not_relatable') ? undefined : json['not_relatable'],
        'related_items': !exists(json, 'related_items') ? undefined : ((json['related_items'] as Array<any>).map(SfvbItemRelatedItemFromJSON)),
    };
}

export function SfvbItemRelatedRequestToJSON(value?: SfvbItemRelatedRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'no_system_calculated_related_items': value.no_system_calculated_related_items,
        'not_relatable': value.not_relatable,
        'related_items': value.related_items === undefined ? undefined : ((value.related_items as Array<any>).map(SfvbItemRelatedItemToJSON)),
    };
}

