/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SfvbPageMultimedia
 */
export interface SfvbPageMultimedia {
    /**
     * The image code, which is what pageImageCode refers to.  Empty for the default image.
     * @type {string}
     * @memberof SfvbPageMultimedia
     */
    code?: string;
    /**
     * True when a template declares this code.  An attached image whose code nothing declares renders nowhere unless a pageimage element names it.
     * @type {boolean}
     * @memberof SfvbPageMultimedia
     */
    declared?: boolean;
    /**
     * True for the page's default image, which a pageimage element with no pageImageCode renders.  This is the thumbnail a subgroup tile shows.
     * @type {boolean}
     * @memberof SfvbPageMultimedia
     */
    _default?: boolean;
    /**
     * What the slot is for, as the declaring template describes it, otherwise the description stored with the image.  Rendered as the alt text.
     * @type {string}
     * @memberof SfvbPageMultimedia
     */
    description?: string;
    /**
     * Width x height in pixels, when the attached file is an image.
     * @type {string}
     * @memberof SfvbPageMultimedia
     */
    dimensions?: string;
    /**
     * The attached file's name within the page's folder.  Empty when nothing is attached.
     * @type {string}
     * @memberof SfvbPageMultimedia
     */
    filename?: string;
    /**
     * Where the source file is served on the storefront.  Absent when nothing is attached.
     * @type {string}
     * @memberof SfvbPageMultimedia
     */
    public_url?: string;
}



/**
 * Check if a given object implements the SfvbPageMultimedia interface.
 */
export function instanceOfSfvbPageMultimedia(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SfvbPageMultimediaFromJSON(json: any): SfvbPageMultimedia {
    return SfvbPageMultimediaFromJSONTyped(json, false);
}

export function SfvbPageMultimediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SfvbPageMultimedia {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'declared': !exists(json, 'declared') ? undefined : json['declared'],
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'dimensions': !exists(json, 'dimensions') ? undefined : json['dimensions'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'public_url': !exists(json, 'public_url') ? undefined : json['public_url'],
    };
}

export function SfvbPageMultimediaToJSON(value?: SfvbPageMultimedia | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'declared': value.declared,
        'default': value._default,
        'description': value.description,
        'dimensions': value.dimensions,
        'filename': value.filename,
        'public_url': value.public_url,
    };
}

