/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaxProviderAvalaraCompany,
    TaxProviderAvalaraCompanyFromJSON,
    TaxProviderAvalaraCompanyFromJSONTyped,
    TaxProviderAvalaraCompanyToJSON,
} from './TaxProviderAvalaraCompany';

/**
 * 
 * @export
 * @interface TaxProviderAvalaraCompaniesResult
 */
export interface TaxProviderAvalaraCompaniesResult {
    /**
     * Tax companies configured by the merchant
     * @type {Array<TaxProviderAvalaraCompany>}
     * @memberof TaxProviderAvalaraCompaniesResult
     */
    companies?: Array<TaxProviderAvalaraCompany>;
}

export function TaxProviderAvalaraCompaniesResultFromJSON(json: any): TaxProviderAvalaraCompaniesResult {
    return TaxProviderAvalaraCompaniesResultFromJSONTyped(json, false);
}

export function TaxProviderAvalaraCompaniesResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxProviderAvalaraCompaniesResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companies': !exists(json, 'companies') ? undefined : ((json['companies'] as Array<any>).map(TaxProviderAvalaraCompanyFromJSON)),
    };
}

export function TaxProviderAvalaraCompaniesResultToJSON(value?: TaxProviderAvalaraCompaniesResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'companies': value.companies === undefined ? undefined : ((value.companies as Array<any>).map(TaxProviderAvalaraCompanyToJSON)),
    };
}

