/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxProviderAnrokProduct
 */
export interface TaxProviderAnrokProduct {
    /**
     * Product description in Anrok
     * @type {string}
     * @memberof TaxProviderAnrokProduct
     */
    description?: string;
    /**
     * Anrok product external id.  This is the value to enter as the item's Anrok Product ID.
     * @type {string}
     * @memberof TaxProviderAnrokProduct
     */
    external_id?: string;
    /**
     * Product name in Anrok
     * @type {string}
     * @memberof TaxProviderAnrokProduct
     */
    name?: string;
    /**
     * Anrok product tax category applied to this product, for example "SaaS - General, B2C"
     * @type {string}
     * @memberof TaxProviderAnrokProduct
     */
    tax_category_name?: string;
}



/**
 * Check if a given object implements the TaxProviderAnrokProduct interface.
 */
export function instanceOfTaxProviderAnrokProduct(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TaxProviderAnrokProductFromJSON(json: any): TaxProviderAnrokProduct {
    return TaxProviderAnrokProductFromJSONTyped(json, false);
}

export function TaxProviderAnrokProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxProviderAnrokProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'external_id': !exists(json, 'external_id') ? undefined : json['external_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'tax_category_name': !exists(json, 'tax_category_name') ? undefined : json['tax_category_name'],
    };
}

export function TaxProviderAnrokProductToJSON(value?: TaxProviderAnrokProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'external_id': value.external_id,
        'name': value.name,
        'tax_category_name': value.tax_category_name,
    };
}

