/* tslint:disable */
/* eslint-disable */
/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    ResponseMetadata,
    ResponseMetadataFromJSON,
    ResponseMetadataFromJSONTyped,
    ResponseMetadataToJSON,
} from './ResponseMetadata';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface WorkflowTaskOpenCountResponse
 */
export interface WorkflowTaskOpenCountResponse {
    /**
     * 
     * @type {ModelError}
     * @memberof WorkflowTaskOpenCountResponse
     */
    error?: ModelError;
    /**
     * 
     * @type {ResponseMetadata}
     * @memberof WorkflowTaskOpenCountResponse
     */
    metadata?: ResponseMetadata;
    /**
     * Open Task Count
     * @type {number}
     * @memberof WorkflowTaskOpenCountResponse
     */
    open_count?: number;
    /**
     * Indicates if API call was successful
     * @type {boolean}
     * @memberof WorkflowTaskOpenCountResponse
     */
    success?: boolean;
    /**
     * 
     * @type {Warning}
     * @memberof WorkflowTaskOpenCountResponse
     */
    warning?: Warning;
}

// Define the constant array of keys
const MY_INTERFACE_KEYS: (keyof WorkflowTaskOpenCountResponse)[] = ["error", "metadata", "open_count", "success", "warning"];

// Exported function to check for excess properties
export function hasExcessProperties(obj: any): boolean {
  const objKeys = Object.keys(obj);
  return objKeys.some(key => !MY_INTERFACE_KEYS.includes(key as keyof MyInterface));
}



/**
 * Check if a given object implements the WorkflowTaskOpenCountResponse interface.
 */
export function instanceOfWorkflowTaskOpenCountResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WorkflowTaskOpenCountResponseFromJSON(json: any): WorkflowTaskOpenCountResponse {
    return WorkflowTaskOpenCountResponseFromJSONTyped(json, false);
}

export function WorkflowTaskOpenCountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowTaskOpenCountResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ModelErrorFromJSON(json['error']),
        'metadata': !exists(json, 'metadata') ? undefined : ResponseMetadataFromJSON(json['metadata']),
        'open_count': !exists(json, 'open_count') ? undefined : json['open_count'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'warning': !exists(json, 'warning') ? undefined : WarningFromJSON(json['warning']),
    };
}

export function WorkflowTaskOpenCountResponseToJSON(value?: WorkflowTaskOpenCountResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ModelErrorToJSON(value.error),
        'metadata': ResponseMetadataToJSON(value.metadata),
        'open_count': value.open_count,
        'success': value.success,
        'warning': WarningToJSON(value.warning),
    };
}

